<?php defined('EMLOG_ROOT') or die('本页面禁止直接访问!');
return array(
	 'post_path' => 'post/', 
	 'post_format' => '{%日志id%}.html', 
	 'post_alias_path' => 'post/', 
	 'post_alias_format' => '{%日志别名%}.html', 
	 'post_comment_page_path' => 'post/{%日志id%}/comments/p/', 
	 'post_comment_page_format' => '{%页码%}.html', 
	 'post_comment_alias_page_path' => 'post/{%日志别名%}/comments/', 
	 'post_comment_alias_page_format' => '{%页码%}.html', 
	 'page_path' => 'page/', 
	 'page_format' => '{%页码%}.html', 
	 'sort_path' => 'sort/{%分类id%}/', 
	 'sort_format' => 'index.html', 
	 'sort_alias_path' => 'sort/{%分类别名%}/', 
	 'sort_alias_format' => 'index.html', 
	 'sort_page_path' => 'sort/{%分类id%}/', 
	 'sort_page_format' => '{%页码%}.html', 
	 'sort_page_alias_path' => 'sort/{%分类别名%}/', 
	 'sort_page_alias_format' => '{%页码%}.html', 
	 'tag_path' => 'tag/{%标签别名%}/', 
	 'tag_format' => 'index.html', 
	 'tag_page_path' => 'tag/{%标签别名%}/page/', 
	 'tag_page_format' => '{%页码%}.html', 
	 'record_path' => 'record/{%日期%}/', 
	 'record_format' => 'index.html', 
	 'record_page_path' => 'record/{%日期%}/page/', 
	 'record_page_format' => '{%页码%}.html', 
	 'author_path' => 'author/{%用户id%}/', 
	 'author_format' => 'index.html', 
	 'author_page_path' => 'author/{%用户id%}/page/', 
	 'author_page_format' => '{%页码%}.html', 
);