<?php

$lang = array(

//---------------------------
//admin/navbar.php
 'address_generated'	=> 'The address generated by the navigation system, can not be modified',//'该导航地址由系统生成，无法修改',

//---------------------------
//admin/views/navbar.php
 'nav_manage'		=> 'Navigation management',//'导航管理',
// 'category_update_ok'	=> 'Category updated successfully',//'排序更新成功',
 'nav_delete_ok'	=> 'Navigation deleted successfully',//'删除导航成功',
 'nav_edit_ok'		=> 'Navigation modifyied successfully',//'修改导航成功',
 'nav_add_ok'		=> 'Navigation added successfully',//'添加导航成功',
 'nav_name_url_empty'	=> 'Navigation name and address can not be empty',//'导航名称和地址不能为空',
 'nav_no_order'		=> 'There is no order of navigation',//'没有可排序的导航',
 'nav_default_nodelete'	=> 'You can not delete the default navigation',//'默认导航不能删除',
 'select_category'	=> 'Please select the category you want to add',//'请选择要添加的分类',
 'select_page'		=> 'Please select the page you want to add',//'请选择要添加的页面',
 'nav_url_invalid'	=> 'Invalid navigation address format (must include the http prefix, etc.)',//'导航地址格式错误(需包含http等前缀)',
 'id'			=> 'ID',//'序号',
// 'navigation'		=> 'Navigation',//'导航',
 'type'			=> 'Type',//'类型',
 'status'		=> 'Status',//'状态',
 'view'			=> 'View',//'查看',
 'address'		=> 'Address',//'地址',
 'system'		=> 'System',//'系统',
// 'category'		=> 'Category',//'分类',
// 'pages'		=> 'Pages',//'页面',
 'page'			=> 'Page',//'页面',
 'custom'		=> 'Custom',//'自定',
 'nav_edit'		=> 'Edit navigation',//'编辑导航',
 'nav_hide_click'	=> 'Click to hide navigation',//'点击隐藏导航',
 'show'			=> 'Show',//'显示',
 'nav_show_click'	=> 'Click to show navigation',//'点击显示导航',
 'hide'			=> 'Hide',//'隐藏',
 'edit'			=> 'Edit',//'编辑',
// 'delete'		=> 'Delete',//'删除',
 'nav_no'		=> 'Has not yet added navigation',//'还没有添加导航',
 'order_change'		=> 'Change order',//'改变排序',
// 'nav_edit'		=> 'Edit navigation',//'编辑导航',
 'nav_add_custom'	=> 'Add custom navigation',//'添加自定义导航',
// 'id'			=> 'ID',//'序号',
 'nav_name'		=> 'Navigation Name',//'导航名称',
 'nav_url_http'		=> 'Address (with http)',//'地址(带http)',
 'no'			=> 'No',//'无',
 'nav_parent'		=> 'Parent navigation',//'父导航',
 'open_new_win'		=> 'Open in new window',//'在新窗口打开',
 'add'			=> 'Add',//'添加',
 'nav_add_category'	=> 'Add category navigation',//'添加分类到导航',
// 'add'		=> 'Add',//'添加',
 'no_categories'	=> 'No categories',//'还没有分类',
 'nav_page_add'		=> 'Add pages to the navigation',//'添加页面到导航',
// 'add'		=> 'Add',//'添加',
 'pages_no'		=> 'No pages',//'还没页面',
// 'add_page'		=> 'Add page',//'新建页面',

//---------------------------
//admin/views/naviedit.php
 'nav_modify'		=> 'Modify navigation',//'修改导航',
// 'nav_name'		=> 'Navigation Name',//'导航名称',
 'nav_address'		=> 'Navigation address',//'导航地址',
// 'open_new_win'	=> 'Open in new window',//'在新窗口打开',
// 'no'			=> 'No',//'无',
// 'save'		=> 'Save',//'保 存',
// 'cancel'		=> 'Cancel',//'取 消',

);
