<?php

$lang = array(

//---------------------------
//admin/navbar.php
 'address_generated'	=> '该导航地址由系统生成，无法修改',//'The address generated by the navigation system, can not be modified',
                                               
//---------------------------
//admin/views/navbar.php
 'nav_manage'		=> '导航管理',//'Navigation management',
// 'category_update_ok'	=> '排序更新成功',//'Category updated successfully',
 'nav_delete_ok'	=> '删除导航成功',//'Navigation deleted successfully',
 'nav_edit_ok'		=> '修改导航成功',//'Navigation modifyied successfully',
 'nav_add_ok'		=> '添加导航成功',//'Navigation added successfully',
 'nav_name_url_empty'	=> '导航名称和地址不能为空',//'Navigation name and address can not be empty',
 'nav_no_order'		=> '没有可排序的导航',//'There is no order of navigation',
 'nav_default_nodelete'	=> '默认导航不能删除',//'You can not delete the default navigation',
 'select_category'	=> '请选择要添加的分类',//'Please select the category you want to add',
 'select_page'		=> '请选择要添加的页面',//'Please select the page you want to add',
 'nav_url_invalid'	=> '导航地址格式错误(需包含http等前缀)',//'Invalid navigation address format (must include the http prefix, etc.)',
 'id'			=> '序号',//'ID',
// 'navigation'		=> '导航',//'Navigation',
 'type'			=> '类型',//'Type',
 'status'		=> '状态',//'Status',
 'view'			=> '查看',//'View',
 'address'		=> '地址',//'Address',
 'system'		=> '系统',//'System',
// 'category'		=> '分类',//'Category',
// 'pages'		=> '页面',//'Pages',
 'page'			=> '页面',//'Page',
 'custom'		=> '自定',//'Custom',
 'nav_edit'		=> '编辑导航',//'Edit navigation',
 'nav_hide_click'	=> '点击隐藏导航',//'Click to hide navigation',
 'show'			=> '显示',//'Show',
 'nav_show_click'	=> '点击显示导航',//'Click to show navigation',
 'hide'			=> '隐藏',//'Hide',
 'edit'			=> '编辑',//'Edit',
// 'delete'		=> '删除',//'Delete',
 'nav_no'		=> '还没有添加导航',//'Has not yet added navigation',
 'order_change'		=> '改变排序',//'Change order',
// 'nav_edit'		=> '编辑导航',//'Edit navigation',
 'nav_add_custom'	=> '添加自定义导航',//'Add custom navigation',
// 'id'			=> '序号',,//'ID',
 'nav_name'		=> '导航名称',//'Navigation Name',
 'nav_url_http'		=> '地址(带http)',//'Address (with http)',
 'no'			=> '无',   //'No',
 'nav_parent'		=> '父导航',//'Parent navigation',
 'open_new_win'		=> '在新窗口打开',//'Open in new window',
 'add'			=> '添加',//'Add',
 'nav_add_category'	=> '添加分类到导航',//'Add category navigation',
// 'add'		=> '添加',//'Add',
 'no_categories'	=> '还没有分类',//'No categories',
 'new_category'		=> '新建分类',//'New Category',
 'nav_page_add'		=> '添加页面到导航',//'Add pages to the navigation',
// 'add'		=> '添加',//'Add',
 'pages_no'		=> '还没页面',//'No pages',
// 'add_page'		=> '新建页面',//'Add page',
                                    
//---------------------------
//admin/views/naviedit.php
 'nav_modify'		=> '修改导航',//'Modify navigation',
// 'nav_name'		=> '导航名称',//'Navigation Name',
 'nav_address'		=> '导航地址',//'导航地址',//'Navigation address',
// 'open_new_win'	=> '在新窗口打开',//'Open in new window',
// 'no'			=> '无',//'No',
// 'save'		=> '保 存',//'Save',
// 'cancel'		=> '取 消',//'Cancel',
                                   
);
