<?php
define('tag_cloud_firstset','');
define('tag_cloud_tname','3D标签云');
define('tag_cloud_width','600');
define('tag_cloud_height','600');
define('tag_cloud_tcolor','0xdd3300');
define('tag_cloud_tcolor2','0x005555');
define('tag_cloud_hicolor','0xff3300');
define('tag_cloud_bgcolor','#f3f3f3');
define('tag_cloud_tspeed','150');
define('tag_cloud_trans','transparent');
define('tag_cloud_args','');
define('tag_cloud_compmode','false');
define('tag_cloud_showwptags','true');
define('tag_cloud_mode','tags');
?>