<?php
//lang_admin.php:
$lang = array(

//---------------------------
//admin/admin_log.php
[56] 'drafts'		=> 'Drafts',//'草稿箱',
[60] 'post_manager'	=> 'Post Manager',//'文章管理',
[157] 'no_permission'	=> 'Insufficient permissions!',//'权限不足！',
[169]//'no_permission'	=> 'Insufficient permissions!',//'权限不足！',
[178]//'no_permission'	=> 'Insufficient permissions!',//'权限不足！',

//---------------------------
//admin/attachment.php
[122] 'attachment_delete_error'		=> 'Attachment delete failed!',//'删除附件失败!',
[129] //'attachment_delete_error'	=> 'Attachment delete failed!',//'删除附件失败!',

//---------------------------
//admin/blogger.php
[17] 'photo_delete'	=> 'Delete image',//'删除头像',

//---------------------------
//admin/comment.php
[40] //'no_permission'		=> 'Insufficient permissions!',//'权限不足！',
[103] 'comment_not_exist'	=> 'This comment does not exist!',//'不存在该评论！',

//---------------------------
//admin/configure.php
[83] 'verification_code_not_supported' => 'Open verification Code failed! Server does not support this feature.',//'开启登录验证码失败!服务器不支持该功能',
[86] 'verification_code_comment_not_supported' =>'Open verification code for comments failed! Server does not support this feature',//'开启评论验证码失败!服务器不支持该功能',

//---------------------------
//admin/data.php
[72] 'backup_directory_not_writable'	=> 'Backup failed. Backup directory (content/backup) is not writable.',//'备份失败。备份目录(content/backup)不可写',
[77] 'backup_create_file_error'		=> 'Create a backup file failed. Backup directory (content/backup) is not writable.',//'创建备份文件失败。备份目录(content/backup)不可写',
[81] 'backup_empty' 			=> 'Nothing to backup. Database tables have no any content.',//'数据表没有任何内容',
[89] 'file_not_exists'			=> 'File does not exist',//'文件不存在',
[93] 'import_only_emlog'		=> 'You can import only emlog SQL backup file',//'只能导入emlog备份的SQL文件',
[105] 'info_illegal'			=> 'Submitted information is illegal',//'非法提交的信息',
[108] 'attachment_exceed_system_limit'	=> 'Attachment size exceeds the system limit ',//'附件大小超过系统 ',//+end space
[108] '_limit'				=> ' limit',//' 限制',//LEAVE THIS EMPTY???
[110] 'upload_failed_code'		=> 'Upload failed. Error code',//'上传文件失败,错误码',
[128] 'import_only_emlog_no_change'	=> 'You can only import emlog backup archive, and the archive file name can not be changed!',//'只能导入emlog备份的压缩包，且不能修改压缩包文件名！',
[131]//'import_only_emlog'		=> 'You can import only emlog SQL backup file',//'只能导入emlog备份的SQL文件',
[158] 'import_failed_not_read'		=> 'Import failed! Can not read the file',//'导入失败！读取文件失败',
[169] 'import_failed_not_emlog'		=> 'Import failed! The backup file is not the emlog backup file!',//'导入失败！该备份文件不是 emlog的备份文件!',
[172] 'import_failed_not_emlog_ver'	=> 'Import failed! The backup file is not the emlog ' . Option::EMLOG_VERSION . ' backup file!',//'导入失败！该备份文件不是emlog ' . Option::EMLOG_VERSION . '  生成的备份!',
[175] 'import_failed_bad_prefix'	=> 'Import failed! The database backup file prefix does not match the current system database prefix ',//'导入失败！备份文件中的数据库前缀与当前系统数据库前缀不匹配 ',

//---------------------------
//admin/globals.php
[44]//'no_permission'	=> 'Insufficient permissions!',//'权限不足！',

//---------------------------
//admin/index.php
[25] 'supported'	=> 'Supported',//'支持',
[28] 'not_supported'	=> 'NOT supported',//'不支持',
[94] 'phpinfo_disabled'	=> 'phpinfo function is disabled!',//'phpinfo函数被禁用!',

//---------------------------
//admin/link.php

//---------------------------
//admin/navbar.php
[98] 'addres_generated'	=> 'The address generated by the navigation system, can not be modified',//'该导航地址由系统生成，无法修改',

//---------------------------
//admin/page.php

//---------------------------
//admin/plugin.php
[91] 'plugin_upload_error'	=> 'Plugin upload failed',//'插件上传失败',

//---------------------------
//admin/save_log.php

//---------------------------
//admin/seo.php

//---------------------------
//admin/sort.php

//---------------------------
//admin/store.php
[20] 'template'		=> 'Template',//'模板',
[21] 'template_view'	=> 'View template',//'查看模板',
[30] 'plugins'		=> 'Plug-ins',//'插件',
[31] 'plugin_view'	=> 'View Plugin',//'查看插件',

//---------------------------
//admin/style.php
[24] 'user'	=> 'User',//'作者',
[26] 'users'	=> 'Users',//'作者',

//---------------------------
//admin/tag.php

//---------------------------
//admin/template.php
[21] 'ok_for_emlog'		=> 'Suitable for emlog',//'适用于emlog',
[24]// 'user'			=> 'User',//'作者'
[24]// 'user'			=> 'User',//'作者',
[205] 'template_upload_failed'	=> 'Template upload failed',//'模板上传失败',

//---------------------------
//admin/trackback.php

//---------------------------
//admin/twitter.php
[32] 'image_share'	=> 'Share Image',//'分享图片',
[68] 'hide'		=> 'Hide',//'隐藏',
[71] 'approve'		=> 'Approve',//'审核',
[76] 'delete'		=> 'Delete',//'删除',
[77] 'reply'		=> 'Reply',//'回复',
[114]// 'hide'		=> 'Hide',//'隐藏',
[115]// 'delete'	=> 'Delete',//'删除',
[116]// 'reply'		=> 'Reply',//'回复',

//---------------------------
//admin/user.php

//---------------------------
//admin/views/add_log.php
[4] 'post_write'		=> 'Write post',//'写文章',
[9] 'enter_post_title'		=> 'Enter the post title',//'输入文章标题',
[14] 'upload_insert'		=> 'Insert upload',//'上传插入',
[27] 'post_tags_separated'	=> 'Posts tags, separated by comma or space. Too many tags will affect the system efficiency',//'文章标签，逗号或空格分隔，过多的标签会影响系统运行效率',
[29] 'tags_have'		=> 'Have tags+',//'已有标签+',
[31] 'category_select'		=> 'Select Category...',//'选择分类...',
[36] 'post_time'		=> 'Posted on',//'发布于',
[46] 'tag_not_set'		=> 'Tags have not been set!',//'还没有设置过标签！',
[50] 'advanced_options'		=> 'Advanced Options',//'高级选项',
[52] 'post_description'		=> 'Post Description',//'文章摘要',
[54] 'post_alias'		=> 'Post Link Alias',//'文章链接别名',
[54] 'post_alias_info'		=> 'Used to customize the post link. Required',//'用于自定义文章链接。需要',
[54] 'post_alias_enable'	=> 'Enable post link alias',//'启用文章链接别名',
[57] 'post_access_password'	=> 'Post Access Password',//'文章访问密码',
[60] 'top_posts'		=> 'Top Posts',//'文章置顶',
[62] 'allow_comments'		=> 'Allow Comments',//'允许评论'
[68] 'post_publish'		=> 'Publish Post',//'发布文章',
[70] 'save_draft'		=> 'Save Draft',//'保存草稿',

//---------------------------
//admin/views/add_page.php
[4] 'add_page'			=> 'Add page',//'新建页面',
[9] 'page_title_info'		=> 'Enter the page title',//'输入页面标题',
[15]//'upload_insert'		=> 'Insert upload',//'上传插入',
[27] 'link_alias'		=> 'Link Alias',//'链接别名',
[27] 'link_alias_info'		=> 'The page link custom address. Required',//'用于自定义该页面的链接地址。需要',
[27] 'link_alias_enable'	=> 'Enable Link Alias',//'启用链接别名',
[32] 'page_enable_comments'	=> 'Page accepted comments',//'页面接受评论'
[38] 'page_publish'		=> 'Publish Page',//'发布页面',
[39] 'save'			=> 'Save',//'保存',

//---------------------------
//admin/views/admin_log.php
[9] ''	=> 'Entry has been deleted successfully',//'删除成功',
[10] ''	=> 'Entry has been has sticked successfully',//'置顶成功',
[11] ''	=> 'Entry has been unsticked successfully',//'取消置顶成功',
[12] ''	=> 'Please, select the entry to operate',//'请选择要处理的文章',
[13] ''	=> 'Please, select an action to operate',//'请选择要执行的操作',
[14] ''	=> 'Entry has been publised successfully',//'发布成功',
[15] ''	=> 'Mobile version has been updated successfully',//'移动成功',
[16] ''	=> 'Entry has been modified successfully',//'更改作者成功',
[17] ''	=> 'Draft has been transferred successfully',//'转入草稿箱成功',
[18] ''	=> 'Draft has been saved successfully',//'草稿保存成功',
[19] ''	=> 'Entry has been saved successfully',//'保存成功',
[20] ''	=> 'Entry has been verifed successfully',//'文章审核成功',
[21] ''	=> 'Entry has been ignored successfully',//'文章驳回成功',
[27] ''	=> 'Whole',//'全部',
[28] ''	=> 'Category',//'分类',
[29] ''	=> 'Tags',//'标签',
[30]// 'user'	=> 'User',//'作者',
[43] ''	=> 'Category',//'分类',
[43] ''	=> 'Uncategorized',//'未分类',
[54] ''	=> 'Tags',//'标签',
[65]//'user'	=> 'User',//'作者',
[85] ''	=> 'Title',//'标题',
[87] ''	=> 'View',//'查看',
[89]//'user'	=> 'User',//'作者',
[90] ''	=> 'Category',//'分类',
[91] ''	=> 'Date',//'时间',
[92] ''	=> 'Comments',//'评论',
[93] ''	=> 'Views',//'阅读',
[100] ''	=> 'Uncategorized',//'未分类',
[107] ''	=> 'Top',//'置顶',
[108] ''	=> 'Attachment',//'附件',
[109] ''	=> 'Pending',//'待审',
[112] ''	=> 'Verify',//'审核',
[114] ''	=> 'Reject',//'驳回',
[120] ''	=> 'Open in a new window',//'在新窗口查看',
[131] ''	=> 'No entries',//'还没有文章',
[137] ''	=> 'Select',//'全选',
[137] ''	=> 'Selected items',//'选中项',
[138]//'delete'	=> 'Delete',//'删除',
[140] ''	=> 'Release',//'发布',
[142] ''	=> 'Move draft',//'转入草稿箱',
[145] ''	=> 'Stick',//'置顶',
[146] ''	=> 'Unstick',//'取消置顶',
[150] ''	=> 'Move to category...',//'移动到分类...',
[154] ''	=> 'Uncategorized',//'未分类',
[159] ''	=> 'Change the author...',//'更改作者为...',
[171] 'have'		=> 'Have',//'有',
[171] 'item_number'	=> '',//'篇',//It is a number of "Items", "Pieces", etc..
[171] 'draft'		=> 'Draft',//'草稿',
[171] 'posts'		=> 'posts',//'文章',
[186] ''	=> 'Please, select the entry to operate',//'请选择要操作的文章',
[188] ''	=> 'Are you sure to want delete selected entries?',//'你确定要删除所选文章吗？',
[195] ''	=> 'Please, select the entry to operate',//'请选择要操作的文章',
[204] ''	=> 'Please, select the entry to operate',//'请选择要操作的文章',

//---------------------------
//admin/views/admin_page.php
[2] ''	=> 'Page management',//'页面管理',
[3] ''	=> 'Page has been removed successfully',//'删除页面成功',
[4] ''	=> 'Page has been released successfully',//'发布页面成功',
[5] ''	=> 'Page has been disabled successfully',//'禁用页面成功',
[6] ''	=> 'Page has been saved successfully',//'页面保存成功',
[13] ''	=> 'Title',//'标题',
[14] ''	=> 'Comments',//'评论',
[15] ''	=> 'Date',//'时间',
[27]//'draft'		=> 'Draft',//'草稿',
[28] ''	=> 'View page',//'查看页面',
[35] ''	=> 'Attachment',//'附件',
[41] ''	=> 'No pages',//'还没有页面',
[48] ''	=> 'Select',//'全选',
[48] ''	=> 'Selected pages',//'选中项',
[49]//'delete'	=> 'Delete',//'删除',
[50] ''	=> 'Into draft',//'转为草稿',
[51] ''	=> 'Release',//'发布',
[53] 'add_page+'	=> 'Add page',//'新建页面+',
[54]//'have'	=> 'Have',//'有',
[54] ''	=> 'pages',//'个页面',
[66] ''	=> 'Please, select the page to operate',//'请选择要操作的页面',
[68] ''	=> 'Are you sure to want delete selected pages?',//'你确定要删除所选页面吗？',

//---------------------------
//admin/views/attlib.php
[22] ''	=> '上传附件',//'上传附件',
[23] ''	=> '批量上传',//'批量上传',
[24] ''	=> '附件库（',//'附件库（',
[24] //'）',//'）',
[28] ''	=> '该文章没有附件',//'该文章没有附件',
[35] ''	=> '插入',//'插入',
[39] ''	=> '插入原图',//'插入原图',
[39] ''	=> '原图',//'原图',
[42] ''	=> '插入缩略图',//'插入缩略图',
[42] ''	=> '缩略图',//'缩略图',
[46] ''	=> '插入',//'插入',
[57]//'delete'	=> 'Delete',//'删除',

//---------------------------
//admin/views/blogger.php
[4] ''	=> '基本设置',//'基本设置',
[5] ''	=> 'SEO设置',//'SEO设置',
[6] ''	=> '后台风格',//'后台风格',
[7] ''	=> '个人设置',//'个人设置',
[9] ''	=> '个人设置',//'个人设置',
[11] ''	=> '个人资料修改成功',//'个人资料修改成功',
[12] ''	=> '头像删除成功',//'头像删除成功',
[13] ''	=> '昵称不能太长',//'昵称不能太长',
[14] ''	=> '电子邮件格式错误',//'电子邮件格式错误',
[15] ''	=> '密码长度不得小于6位',//'密码长度不得小于6位',
[16] ''	=> '两次输入的密码不一致',//'两次输入的密码不一致',
[17] ''	=> '该登录名已存在',//'该登录名已存在',
[18] ''	=> '该昵称已存在',//'该昵称已存在',
[24] ''	=> '头像',//'头像',
[25] ''	=> '(支持JPG、PNG格式图片)',//'(支持JPG、PNG格式图片)',
[27] ''	=> '昵称',//'昵称',
[28] ''	=> '邮箱',//'邮箱',
[29] ''	=> '个人描述',//'个人描述',
[30] ''	=> '登陆名',//'登陆名',
[31] ''	=> '新密码（不小于6位，不修改请留空）',//'新密码（不小于6位，不修改请留空）',
[32] ''	=> '再输入一次新密码',//'再输入一次新密码',
[33] ''	=> '保存资料',//'保存资料',

//---------------------------
//admin/views/comment.php
[2] ''	=> '评论管理',//'评论管理',
[3] ''	=> '删除评论成功',//'删除评论成功',
[4] ''	=> '审核评论成功',//'审核评论成功',
[5] ''	=> '隐藏评论成功',//'隐藏评论成功',
[6] ''	=> '修改评论成功',//'修改评论成功',
[7] ''	=> '回复评论成功',//'回复评论成功',
[8] ''	=> '请选择要执行操作的评论',//'请选择要执行操作的评论',
[9] ''	=> '请选择要执行的操作',//'请选择要执行的操作',
[10] ''	=> '回复内容不能为空',//'回复内容不能为空',
[11] ''	=> '内容过长',//'内容过长',
[12] ''	=> '评论内容不能为空',//'评论内容不能为空',
[21] ''	=> '全部',//'全部',
[22] ''	=> '待审',//'待审',
[28] ''	=> '已审',//'已审',
[35] ''	=> '内容',//'内容',
[36] ''	=> '评论者',//'评论者',
[37] ''	=> '所属文章',//'所属文章',
[44] ''	=> '[待审]',//'[待审]',
[46] ''	=> '来自',//'来自',
[58]//'delete'	=> 'Delete',//'删除',
[60] ''	=> '审核',//'审核',
[62]//'hide'	=> 'Hide',//'隐藏',
[64]//'reply'	=> 'Reply',//'回复',
[65] ''	=> '编辑',//'编辑',
[69] ''	=> '删除来自该IP的所有评论',//'删除来自该IP的所有评论',
[70] ''	=> '查看该文章',//'查看该文章',
[73] ''	=> '还没有收到评论',//'还没有收到评论',
[78] ''	=> '全选',//'全选',
[78] ''	=> '选中项',//'选中项',
[79]//'delete'	=> 'Delete',//'删除',
[80]//'hide'	=> 'Hide',//'隐藏',
[81] ''	=> '审核',//'审核',
[84]//'have'	=> 'Have',//'有',
[84] ''	=> '条评论',//'条评论',
[97] ''	=> '请选择要操作的评论',//'请选择要操作的评论',
[100] ''	=> '你确定要删除所选评论吗？',//'你确定要删除所选评论吗？',

//---------------------------
//admin/views/comment_edit.php
[2] ''	=> '编辑评论',//'编辑评论',
[7] ''	=> '评论人',//'评论人',
[8] ''	=> '电子邮件',//'电子邮件',
[9] ''	=> '主页',//'主页',
[10] ''	=> '评论内容',//'评论内容',
[12] ''	=> '保 存',//'保 存',
[13] ''	=> '取 消',//'取 消',

//---------------------------
//admin/views/comment_reply.php
[2] ''	=> '回复评论',//'回复评论',
[7] ''	=> '评论人',//'评论人',
[8] ''	=> '时间',//'时间',
[9] ''	=> '内容',//'内容',
[15]//'reply'	=> 'Reply',//'回复',
[17] ''	=> '回复并审核',//'回复并审核',
[19] ''	=> '取 消',//'取 消',

//---------------------------
//admin/views/configure.php
[4] ''	=> '基本设置',//'基本设置',
[5] ''	=> 'SEO设置',//'SEO设置',
[6] ''	=> '后台风格',//'后台风格',
[7] ''	=> '个人设置',//'个人设置',
[8] ''	=> '设置保存成功',//'设置保存成功',
[13] ''	=> '站点标题',//'站点标题',
[17] ''	=> '站点副标题',//'站点副标题',
[21] ''	=> '站点地址',//'站点地址',
[25] ''	=> '每页显示',//'每页显示',
[26] ''	=> '篇文章',//'篇文章',
[29] ''	=> '你所在时区',//'你所在时区',
[33] 'tz-12'	=> '[-12:00] Dateline West',//'(标准时-12) 日界线西',
[34] 'tz-11'	=> '[-11:00] Midway Island, Samoa',//'(标准时-11) 中途岛、萨摩亚群岛',
[35] 'tz-10'	=> '[-10:00] Hawaii',//'(标准时-10) 夏威夷',
[36] 'tz-9'	=> '[-09:00] Alaska',//'(标准时-9) 阿拉斯加',
[37] 'tz-8'	=> '[-08:00] Pacific Time (U.S. & Canada)',//'(标准时-8) 太平洋时间(美国和加拿大)',
[38] 'tz-7'	=> '[-07:00] Mountain Time (U.S. & Canada)',//'(标准时-7) 山地时间(美国和加拿大)',
[39] 'tz-6'	=> '[-06:00] Central Time (U.S. & Canada), Mexico City',//'(标准时-6) 中部时间(美国和加拿大)、墨西哥城',
[40] 'tz-5'	=> '[-05:00] Eastern Time (U.S. & Canada), Bogota',//'(标准时-5) 东部时间(美国和加拿大)、波哥大',
[41] 'tz-4'	=> '[-04:00] Atlantic Time (Canada), Caracas',//'(标准时-4) 大西洋时间(加拿大)、加拉加斯',
[42] 'tz-3.5'	=> '[-03:30] Newfoundland',//'(标准时-3:30) 纽芬兰',
[43] 'tz-3'	=> '[-03:00] Brazil, Buenos Aires, Georgetown',//'(标准时-3) 巴西、布宜诺斯艾利斯、乔治敦',
[44] 'tz-2'	=> '[-02:00] Mid-Atlantic',//'(标准时-2) 中大西洋',
[45] 'tz-1'	=> '[-01:00] Azores, Cape Verde Islands',//'(标准时-1) 亚速尔群岛、佛得角群岛',
[46] 'tz0'	=> '[ 00:00] Western European Time, London, Casablanca',//'(标准时) 西欧时间、伦敦、卡萨布兰卡',
[47] 'tz1'	=> '[+01:00] Central European Time, Angola, Libya',//'(标准时+1) 中欧时间、安哥拉、利比亚',
[48] 'tz2'	=> '[+02:00] Eastern European Time, Cairo, Athens',//'(标准时+2) 东欧时间、开罗，雅典',
[49] 'tz3'	=> '[+03:00] Baghdad, Kuwait',//'(标准时+3) 巴格达、科威特、莫斯科',
[50] 'tz3.5'	=> '[+03:30] Tehran',//'(标准时+3:30) 德黑兰',
[51] 'tz4'	=> '[+04:00] Abu Dhabi, Baku, Moscow, Muscat',//'(标准时+4) 阿布扎比、马斯喀特、巴库',
[52] 'tz4.5'	=> '[+04:30] Kabul',//'(标准时+4:30) 喀布尔',
[53] 'tz5'	=> '[+05:00] Ekaterinburg, Islamabad, Karachi',//'(标准时+5) 叶卡捷琳堡、伊斯兰堡、卡拉奇',
[54] 'tz5.5'	=> '[+05:30] Bombay, Calcutta, New Delhi',//'(标准时+5:30) 孟买、加尔各答、新德里',
[55] 'tz6'	=> '[+06:00] Almaty, Dhaka, New Elijah Abel',//'(标准时+6) 阿拉木图、 达卡、新亚伯利亚',
[56] 'tz7'	=> '[+07:00] Bangkok, Hanoi, Jakarta',//'(标准时+7) 曼谷、河内、雅加达',
[57] 'tz8'	=> '[+08:00] Beijing, Chongqing, Hong Kong, Singapore',//'(标准时+8) 北京、重庆、香港、新加坡',
[58] 'tz9'	=> '[+09:00] Tokyo, Seoul, Osaka, Yakutsk',//'(标准时+9) 东京、汉城、大阪、雅库茨克',
[59] 'tz9.5'	=> '[+09:30] Adelaide, Darwin',//'(标准时+9:30) 阿德莱德、达尔文',
[60] 'tz10'	=> '[+10:00] Sydney, Guam',//'(标准时+10) 悉尼、关岛',
[61] 'tz11'	=> '[+11:00] Magadan, Solomon Islands',//'(标准时+11) 马加丹、索罗门群岛',
[62] 'tz12'	=> '[+12:00] Auckland, Wellington, Kamchatka',//'(标准时+12) 奥克兰、惠灵顿、堪察加半岛',
[70] ''	=> '本地时间',//'本地时间',
[74] ''	=> '功能开关',//'功能开关',
[76] ''	=> '登录验证码',//'登录验证码',
[77] ''	=> '图片附件缩略图',//'图片附件缩略图',
[78] ''	=> 'Gzip压缩',//'Gzip压缩',
[79] ''	=> '离线写作',//'离线写作',
[80] ''	=> '手机访问版，地址',//'手机访问版，地址',
[80] ''	=> '用手机访问你的站点',//'用手机访问你的站点',
[81] ''	=> '自动摘要，截取文章的前',//'自动摘要，截取文章的前',
[82] ''	=> '个字作为摘要',//'个字作为摘要',
[89] ''	=> '微语',//'微语',
[91] ''	=> '开启微语，',//'开启微语，',
[92] ''	=> '每页显示',//'每页显示',
[92] ''	=> '条微语',//'条微语',
[93] ''	=> '开启微语回复，',//'开启微语回复，',
[94] ''	=> '回复验证码，',//'回复验证码，',
[95] ''	=> '回复审核',//'回复审核',
[102] ''	=> 'RSS',//'RSS',
[104] ''	=> '输出',//'输出',
[104] ''	=> '篇文章，且输出',//'篇文章，且输出',
[106] ''	=> '全文',//'全文',
[107] ''	=> '摘要',//'摘要',
[115] ''	=> '评论',//'评论',
[117] ''	=> '开启评论，发表评论间隔',//'开启评论，发表评论间隔',
[117] ''	=> '秒',//'秒',
[118] ''	=> '评论审核',//'评论审核',
[119] ''	=> '评论验证码',//'评论验证码',
[120] ''	=> '评论人头像',//'评论人头像',
[121] ''	=> '评论内容必须包含中文',//'评论内容必须包含中文',
[122] ''	=> '评论分页，',//'评论分页，',
[123] ''	=> '每页显示',//'每页显示',
[123] ''	=> '条评论，',//'条评论，',
[124] ''	=> '较新的',//'较新的',
[124] ''	=> '较旧的',//'较旧的',
[124] ''	=> '排在前面',//'排在前面',
[131] ''	=> 'ICP备案号',//'ICP备案号',
[135] ''	=> '首页底部信息',//'首页底部信息',
[138] ''	=> '(支持html，可用于添加流量统计代码)',//'(支持html，可用于添加流量统计代码)',
[145] ''	=> '保存设置',//'保存设置',

//---------------------------
//admin/views/css/css-main.css

//---------------------------
//admin/views/data.php
[2] ''	=> '数据备份',//'数据备份',
[3] ''	=> '备份文件删除成功',//'备份文件删除成功',
[4] ''	=> '数据备份成功',//'数据备份成功',
[5] ''	=> '备份导入成功',//'备份导入成功',
[6] ''	=> '请选择要删除的备份文件',//'请选择要删除的备份文件',
[7] ''	=> '备份文件名错误(应由英文字母、数字、下划线组成)',//'备份文件名错误(应由英文字母、数字、下划线组成)',
[8] ''	=> '服务器不支持zip，无法导入zip备份',//'服务器不支持zip，无法导入zip备份',
[9] ''	=> '上传备份失败',//'上传备份失败',
[10] ''	=> '错误的备份文件',//'错误的备份文件',
[11] ''	=> '服务器不支持zip，无法导出zip备份',//'服务器不支持zip，无法导出zip备份',
[18] ''	=> '备份文件',//'备份文件',
[19] ''	=> '备份时间',//'备份时间',
[20] ''	=> '文件大小',//'文件大小',
[37] ''	=> '导入',//'导入',
[40] ''	=> '还没有备份',//'还没有备份',
[45] ''	=> '全选',//'全选',
[45] ''	=> '选中项',//'选中项',
[45]//'delete'	=> 'Delete',//'删除',
[47] ''	=> '备份数据+',//'备份数据+',
[47] ''	=> '　',//'　',
[47] ''	=> '导入本地备份+',//'导入本地备份+',
[50] ''	=> '选择要备份的数据库表',//'选择要备份的数据库表',
[55] ''	=> '导出备份文件到',//'导出备份文件到',
[57] ''	=> '本地',//'本地',
[58] ''	=> '服务器',//'服务器',
[61] ''	=> '压缩(zip格式)',//'压缩(zip格式)',
[62] ''	=> '备份文件名',//'备份文件名',
[63] ''	=> '开始备份',//'开始备份',
[68] ''	=> '导入',//'导入',
[68] ''	=> '(支持emlog导出的sql及zip格式备份)',//'(支持emlog导出的sql及zip格式备份)',
[71] ''	=> '数据缓存',//'数据缓存',
[72] ''	=> '缓存更新成功',//'缓存更新成功',
[76] ''	=> '缓存可以大幅度提高站点的加载速度。通常系统会自动更新缓存，无需手动。有些特殊情况，比如缓存文件被修改、手动修改过数据库、页面出现异常等才需要手动更新。',//'缓存可以大幅度提高站点的加载速度。通常系统会自动更新缓存，无需手动。有些特殊情况，比如缓存文件被修改、手动修改过数据库、页面出现异常等才需要手动更新。',
[77] ''	=> '更新缓存',//'更新缓存',
[91] ''	=> '请选择要操作的备份文件',//'请选择要操作的备份文件',
[94] ''	=> '你确定要删除所选备份文件吗？',//'你确定要删除所选备份文件吗？',

//---------------------------
//admin/views/edit_log.php
[7] 'draft_edit'		=> 'Edit draft',//'编辑草稿',
[7] 'post_edit'			=> 'Edit post',//'编辑文章',
[11]//'enter_post_title'	=> 'Enter the post title',//'输入文章标题',
[16]//'upload_insert'		=> 'Insert upload',//'上传插入',
[29]//'post_tags_separated'	=> 'Posts tags, separated by comma or space. Too many tags will affect the system efficiency',//'文章标签，逗号或空格分隔，过多的标签会影响系统运行效率',
[31]//'tags_have'		=> 'Have tags+',//'已有标签+',
[34]//'category_select'		=> 'Select Category...',//'选择分类...',
[41]//'post_time'		=> 'Posted on',//'发布于',
[51]//'tag_not_set'		=> 'Tags have not been set!',//'还没有设置过标签！',
[55]//'advanced_options'	=> 'Advanced Options',//'高级选项',
[57]//'post_description'	=> 'Post Description',//'文章摘要',
[59]//'post_alias'		=> 'Post Link Alias',//'文章链接别名',
[59] ''	=> '用于自定义该篇文章的链接地址。需要',//'用于自定义该篇文章的链接地址。需要',
[59]//'post_alias_enable'	=> 'Enable post link alias',//'启用文章链接别名',
[62]//'post_access_password'	=> 'Post Access Password',//'文章访问密码',
[65]//'top_posts'		=> 'Top Posts',//'文章置顶',
[67]//'allow_comments'		=> 'Allow Comments',//'允许评论',
[75] ''	=> '保存并返回',//'保存并返回',
[76]//'save'			=> 'Save',//'保存',
[78] ''	=> '发布',

//---------------------------
//admin/views/edit_page.php
[4] ''	=> '编辑页面',//'编辑页面',
[9]//'page_title_info'	=> 'Enter the page title',//'输入页面标题',
[14]//'upload_insert'	=> 'Insert upload',//'上传插入',
[26]// 'link_alias'	=> 'Link Alias',//'链接别名',
[26]//'link_alias_info'	=> 'The page link custom address. Required',//'用于自定义该页面的链接地址。需要',
[26] //'link_alias_enable'	=> 'Enable Link Alias',//'启用链接别名',
[31] //'page_enable_comments'	=> 'Page accepted comments',//'页面接受评论',
[38] ''	=> '保存并返回',//'保存并返回',
[39] //'save'	=> 'Save',//'保存',

//---------------------------
//admin/views/footer.php
[3] ''	=> '欢迎使用',//'欢迎使用',

//---------------------------
//admin/views/header.php
[10] 'admin_center'		=> 'AdminCP',//'管理中心',
[22] 'return_to_admin_center'	=> 'Return to AdminCP',//'返回管理首页',
[24] 'to_site_new_window'	=> 'Visit the site in a new window',//'在新窗口浏站点',
[27] 'to_site'			=> 'View My site',//'查看我的站点',
[37] 'settings'			=> 'Settings',//'设置',
[39] 'logout'			=> 'Logout',//'退出',
[45]//'post_write'		=> 'Write post',//'写文章',
[47]//'draft'			=> 'Draft',//'草稿',
[56] ''	=> '文章',//'文章',
[62] ''	=> '篇文章待审',//'篇文章待审',
[65] ''	=> '标签',//'标签',
[66] ''	=> '分类',//'分类',
[68] ''	=> '评论',//'评论',
[74] ''	=> '条评论待审',//'条评论待审',
[77] 'twitter'		=> 'Twitter',//'微语',
[78] ''	=> '侧边栏',//'侧边栏',
[79] ''	=> '导航',//'导航',
[80] ''	=> '页面',//'页面',
[81] ''	=> '链接',//'链接',
[82] ''	=> '用户',//'用户',
[83] ''	=> '数据',//'数据',
[84] ''	=> '插件',//'插件',
[85] ''	=> '模板',//'模板',
[86] ''	=> '应用中心',//'应用中心',
[88] ''	=> '扩展功能',//'扩展功能',
[102] <!--边栏折叠-->

//---------------------------
//admin/views/index.php
[10] ''	=> '用微语记录生活 ……',//'用微语记录生活 ……',
[11] ''	=> '发布',//'发布',
[11] ''	=> '取消',//'取消',
[11] ''	=> '(你还可以输入140字)',//'(你还可以输入140字)',
[20] ''	=> '站点信息',//'站点信息',
[22]//'have'	=> 'Have',//'有',
[22] ''	=> '篇文章，',//'篇文章，',
[22] ''	=> '条评论，',//'条评论，',
[22] ''	=> '条微语',//'条微语',
[23] ''	=> 'PHP版本',//'PHP版本',
[24] ''	=> 'MySQL版本',//'MySQL版本',
[25] ''	=> '服务器环境',//'服务器环境',
[26] ''	=> 'GD图形处理库',//'GD图形处理库',
[27] ''	=> '服务器允许上传最大文件',//'服务器允许上传最大文件',
[28] ''	=> '更多信息&raquo;',//'更多信息&raquo;',
[32] ''	=> '官方消息',//'官方消息',
[37] ''	=> '您正在使用emlog',//'您正在使用emlog',
[37] ''	=> '检查更新',//'检查更新',
[44] ''	=> '正在读取...',//'正在读取...',
[58] ''	=> '正在检查，请稍后',//'正在检查，请稍后',
[62] ''	=> '目前还没有适合您当前版本的更新！',//'目前还没有适合您当前版本的更新！',
[64] ''	=> '有可用的emlog更新版本 ',//'有可用的emlog更新版本 ',
[64] ''	=> ' ，更新之前请您做好数据备份工作，',//' ，更新之前请您做好数据备份工作，',
[64] ''	=> '现在更新',//'现在更新',
[66] ''	=> '检查失败，可能是网络问题',//'检查失败，可能是网络问题',
[71] ''	=> '系统正在更新中，请耐心等待',//'系统正在更新中，请耐心等待',
[76] ''	=> '恭喜您！更新成功了，请',//'恭喜您！更新成功了，请',
[76] ''	=> '刷新页面',//'刷新页面',
[76] ''	=> '开始体验新版emlog',//'开始体验新版emlog',
[78] ''	=> '下载更新失败，可能是服务器网络问题',//'下载更新失败，可能是服务器网络问题',
[80] ''	=> '解压更新失败，可能是服务器不支持zip模块',//'解压更新失败，可能是服务器不支持zip模块',
[82] ''	=> '更新失败，目录不可写',//'更新失败，目录不可写',
[84] ''	=> '更新失败',//'更新失败',
[99] ''	=> '你还可以输入',//'你还可以输入',
[99] ''	=> '字',//'字',
[101] ''	=> '已超出',//'已超出',
[101] ''	=> '字',//'字',
[107] ''	=> '(你还可以输入140字)',//'(你还可以输入140字)',
[108] ''	=> '用微语记录生活……',//'用微语记录生活……',
[120] ''	=> '（',//'（',
[120] ''	=> '篇文章，',//'篇文章，',
[120] ''	=> '条评论）',//'条评论）',

//---------------------------
//admin/views/linkedit.php
[2] ''	=> '编辑链接',//'编辑链接',
[6] ''	=> '名称',//'名称',
[7] ''	=> '地址',//'地址',
[8] ''	=> '链接描述',//'链接描述',
[11] ''	=> '保 存',//'保 存',
[12] ''	=> '取 消',//'取 消',

//---------------------------
//admin/views/links.php
[2] ''	=> '友情链接管理',//'友情链接管理',
[3] ''	=> '排序更新成功',//'排序更新成功',
[4] ''	=> '删除成功',//'删除成功',
[5] ''	=> '修改成功',//'修改成功',
[6] ''	=> '添加成功',//'添加成功',
[7] ''	=> '站点名称和地址不能为空',//'站点名称和地址不能为空',
[8] ''	=> '没有可排序的链接',//'没有可排序的链接',
[15] ''	=> '序号',//'序号',
[16] ''	=> '链接',//'链接',
[17] ''	=> '状态',//'状态',
[18] ''	=> '查看',//'查看',
[19] ''	=> '描述',//'描述',
[31] ''	=> '修改链接',//'修改链接',
[34] ''	=> '点击隐藏链接',//'点击隐藏链接',
[34] ''	=> '显示',//'显示',
[36] ''	=> '点击显示链接',//'点击显示链接',
[36]//'hide'	=> 'Hide',//'隐藏',
[40] ''	=> '查看链接',//'查看链接',
[45] ''	=> '编辑',//'编辑',
[46]//'delete'	=> 'Delete',//'删除',
[50] ''	=> '还没有添加链接',//'还没有添加链接',
[54] ''	=> '改变排序',//'改变排序',
[57] ''	=> '添加链接+',//'添加链接+',
[59] ''	=> '序号',//'序号',
[61] ''	=> '名称',//'名称',
[63] ''	=> '地址',//'地址',
[65] ''	=> '描述',//'描述',
[67] ''	=> '添加链接',//'添加链接',

//---------------------------
//admin/views/login.php
[8] ''	=> '登录',//'登录',
[16] ''	=> '用户名',//'用户名',
[18] ''	=> '密码',//'密码',
[23] ''	=> '记住我',//'记住我',
[24] ''	=> '登 录',//'登 录',
[29] ''	=> '&laquo;返回首页',//'&laquo;返回首页',
[29] ''	=> '忘记密码?',//'忘记密码?',

//---------------------------
//admin/views/navbar.php
[2] ''	=> '导航管理',//'导航管理',
[3] ''	=> '排序更新成功',//'排序更新成功',
[4] ''	=> '删除导航成功',//'删除导航成功',
[5] ''	=> '修改导航成功',//'修改导航成功',
[6] ''	=> '添加导航成功',//'添加导航成功',
[7] ''	=> '导航名称和地址不能为空',//'导航名称和地址不能为空',
[8] ''	=> '没有可排序的导航',//'没有可排序的导航',
[9] ''	=> '默认导航不能删除',//'默认导航不能删除',
[10] ''	=> '请选择要添加的分类',//'请选择要添加的分类',
[11] ''	=> '请选择要添加的页面',//'请选择要添加的页面',
[12] ''	=> '导航地址格式错误(需包含http等前缀)',//'导航地址格式错误(需包含http等前缀)',
[19] ''	=> '序号',//'序号',
[20] ''	=> '导航',//'导航',
[21] ''	=> '类型',//'类型',
[22] ''	=> '状态',//'状态',
[23] ''	=> '查看',//'查看',
[24] ''	=> '地址',//'地址',
[37] ''	=> '系统',//'系统',
[40] ''	=> '分类',//'分类',
[43] ''	=> '页面',//'页面',
[46] ''	=> '自定',//'自定',
[53] ''	=> '编辑导航',//'编辑导航',
[57] ''	=> '点击隐藏导航',//'点击隐藏导航',
[57] ''	=> '显示',//'显示',
[59] ''	=> '点击显示导航',//'点击显示导航',
[59]//'hide'	=> 'Hide',//'隐藏',
[68] ''	=> '编辑',//'编辑',
[70]//'delete'	=> 'Delete',//'删除',
[75] ''	=> '还没有添加导航',//'还没有添加导航',
[79] ''	=> '改变排序',//'改变排序',
[84] ''	=> '添加自定义导航+',//'添加自定义导航+',
[86] ''	=> '序号',//'序号',
[87] ''	=> '导航名称',//'导航名称',
[89] ''	=> '地址(带http)',//'地址(带http)',
[90] ''	=> '在新窗口打开',//'在新窗口打开',
[91] ''	=> '添加',//'添加',
[97] ''	=> '添加分类到导航+',//'添加分类到导航+',
[108] ''	=> '添加',//'添加',
[110] ''	=> '还没有分类，',//'还没有分类，',
[110] ''	=> '新建分类',//'新建分类',
[117] ''	=> '添加页面到导航+',//'添加页面到导航+',
[128] ''	=> '添加',//'添加',
[130] ''	=> '还没页面，',//'还没页面，',
[130]//'add_page'	=> 'Add page',//'新建页面',

//---------------------------
//admin/views/naviedit.php
[2] ''	=> '修改导航',//'修改导航',
[6] ''	=> '导航名称',//'导航名称',
[8] ''	=> '导航地址，',//'导航地址，',
[9] ''	=> '在新窗口打开',//'在新窗口打开',
[13] ''	=> '保 存',//'保 存',
[14] ''	=> '取 消',//'取 消',

//---------------------------
//admin/views/plugin.php
[2] ''	=> '插件管理',//'插件管理',
[3] ''	=> '插件上传成功，请激活使用',//'插件上传成功，请激活使用',
[4] ''	=> '插件激活成功',//'插件激活成功',
[5] ''	=> '删除成功',//'删除成功',
[6] ''	=> '插件激活失败',//'插件激活失败',
[7] ''	=> '插件禁用成功',//'插件禁用成功',
[8] ''	=> '删除失败，请检查插件文件权限',//'删除失败，请检查插件文件权限',
[15] ''	=> '状态',//'状态',
[16] ''	=> '版本',//'版本',
[17] ''	=> '描述',//'描述',
[28] ''	=> '点击激活插件',//'点击激活插件',
[33] ''	=> '点击禁用插件',//'点击禁用插件',
[37] ''	=> '点击设置插件',//'点击设置插件',
[48] ''	=> '更多信息&raquo;',//'更多信息&raquo;',
[50] ''	=> '适用于emlog',//'适用于emlog',
[52]//'user'	=> 'User',//'作者',
[61]//'delete'	=> 'Delete',//'删除',
[66] ''	=> '还没有安装插件',//'还没有安装插件',
[71] ''	=> '安装插件',//'安装插件',

//---------------------------
//admin/views/plugin_install.php
[3] ''	=> '安装插件',//'安装插件',
[4] ''	=> '只支持zip压缩格式的插件包',//'只支持zip压缩格式的插件包',
[5] ''	=> '上传失败，插件目录(content/plugins)不可写',//'上传失败，插件目录(content/plugins)不可写',
[6] ''	=> '空间不支持zip模块，请按照提示手动安装插件',//'空间不支持zip模块，请按照提示手动安装插件',
[7] ''	=> '请选择一个zip插件安装包',//'请选择一个zip插件安装包',
[8] ''	=> '安装失败，插件安装包不符合标准',//'安装失败，插件安装包不符合标准',
[14] ''	=> '手动安装插件',//'手动安装插件',
[15] ''	=> '1、把解压后的插件文件夹上传到 content/plugins 目录下。',//'1、把解压后的插件文件夹上传到 content/plugins 目录下。',
[16] ''	=> '2、登录后台进入插件管理,插件管理里已经有了该插件，点击激活即可。',//'2、登录后台进入插件管理,插件管理里已经有了该插件，点击激活即可。',
[24] ''	=> '上传安装',//'上传安装',
[24] ''	=> '（上传一个zip压缩格式的插件安装包）',//'（上传一个zip压缩格式的插件安装包）',
[28] ''	=> '获取更多插件',//'获取更多插件',
[28] ''	=> '应用中心&raquo;',//'应用中心&raquo;',

//---------------------------
//admin/views/seo.php
[4] ''	=> '基本设置',//'基本设置',
[5] ''	=> 'SEO设置',//'SEO设置',
[6] ''	=> '后台风格',//'后台风格',
[7] ''	=> '个人设置',//'个人设置',
[8] ''	=> '设置保存成功',//'设置保存成功',
[9] ''	=> '保存失败：根目录下的.htaccess不可写',//'保存失败：根目录下的.htaccess不可写',
[13] ''	=> '文章链接设置',//'文章链接设置',
[15] ''	=> '你可以在这里修改文章链接的形式，如果修改后文章无法访问，那可能是你的服务器环境不支持URL重写，请修改回默认形式、关闭文章连接别名。',//'你可以在这里修改文章链接的形式，如果修改后文章无法访问，那可能是你的服务器环境不支持URL重写，请修改回默认形式、关闭文章连接别名。',
[16] ''	=> '启用链接别名后可以自定义文章和页面的链接地址。',//'启用链接别名后可以自定义文章和页面的链接地址。',
[19] ''	=> '默认形式',//'默认形式',
[20] ''	=> '文件形式',//'文件形式',
[21] ''	=> '目录形式',//'目录形式',
[22] ''	=> '分类形式',//'分类形式',
[24]//'post_alias_enable'	=> 'Enable post link alias',//'启用文章链接别名',
[25] ''	=> '启用文章链接别名html后缀',//'启用文章链接别名html后缀',
[28] ''	=> 'Meta设置',//'Meta设置',
[30] ''	=> '站点浏览器标题(title)',//'站点浏览器标题(title)',
[31] ''	=> '站点关键字(keywords)',//'站点关键字(keywords)',
[32] ''	=> '站点浏览器描述(description)',//'站点浏览器描述(description)',
[33] ''	=> '文章浏览器标题方案',//'文章浏览器标题方案',
[35] ''	=> '文章标题',//'文章标题',
[36] ''	=> '文章标题 - 站点标题',//'文章标题 - 站点标题',
[37] ''	=> '文章标题 - 站点浏览器标题',//'文章标题 - 站点浏览器标题',
[40] ''	=> '保存设置',//'保存设置',

//---------------------------
//admin/views/sort.php
[3] ''	=> '分类管理',//'分类管理',
[4] ''	=> '排序更新成功',//'排序更新成功',
[5] ''	=> '删除分类成功',//'删除分类成功',
[6] ''	=> '修改分类成功',//'修改分类成功',
[7] ''	=> '添加分类成功',//'添加分类成功',
[8] ''	=> '分类名称不能为空',//'分类名称不能为空',
[9] ''	=> '没有可排序的分类',//'没有可排序的分类',
[10] ''	=> '别名格式错误',//'别名格式错误',
[11] ''	=> '别名不能重复',//'别名不能重复',
[12] ''	=> '别名不得包含系统保留关键字',//'别名不得包含系统保留关键字',
[19] ''	=> '序号',//'序号',
[20] ''	=> '名称',//'名称',
[21] ''	=> '描述',//'描述',
[22] ''	=> '别名',//'别名',
[23] ''	=> '查看',//'查看',
[24] ''	=> '文章',//'文章',
[49] ''	=> '编辑',//'编辑',
[50]//'delete'	=> 'Delete',//'删除',
[71] ''	=> '编辑',//'编辑',
[72]//'delete'	=> 'Delete',//'删除',
[77] ''	=> '还没有添加分类',//'还没有添加分类',
[81] ''	=> '改变排序',//'改变排序',
[84] ''	=> '添加分类+',//'添加分类+',
[86] ''	=> '序号',//'序号',
[87] ''	=> '名称',//'名称',
[88] ''	=> '别名 (可不填，用于URL的友好显示)',//'别名 (可不填，用于URL的友好显示)',
[91] ''	=> '无',//'无',
[101] ''	=> '父分类',//'父分类',
[103] ''	=> '分类描述',//'分类描述',
[105] ''	=> '添加新分类',//'添加新分类',
[128] ''	=> '别名错误，应由字母、数字、下划线、短横线组成',//'别名错误，应由字母、数字、下划线、短横线组成',
[131] ''	=> '别名错误，不能为纯数字',//'别名错误，不能为纯数字',
[134] ''	=> '别名错误，与系统链接冲突',//'别名错误，与系统链接冲突',

//---------------------------
//admin/views/sortedit.php
[2] ''	=> '分类名称不能为空',//'分类名称不能为空',
[3] ''	=> '别名格式错误',//'别名格式错误',
[4] ''	=> '别名不能重复',//'别名不能重复',
[5] ''	=> '别名不得包含系统保留关键字',//'别名不得包含系统保留关键字',
[6] ''	=> '编辑分类',//'编辑分类',
[10] ''	=> '名称',//'名称',
[11] ''	=> '别名',//'别名',
[15] ''	=> '无',//'无',
[23] ''	=> '父分类',//'父分类',
[26] ''	=> '分类描述',//'分类描述',
[30] ''	=> '保 存',//'保 存',
[31] ''	=> '取 消',//'取 消',
[55] ''	=> '别名错误，应由字母、数字、下划线、短横线组成',//'别名错误，应由字母、数字、下划线、短横线组成',
[58] ''	=> '别名错误，不能为纯数字',//'别名错误，不能为纯数字',
[61] ''	=> '别名错误，与系统链接冲突',//'别名错误，与系统链接冲突',

//---------------------------
//admin/views/store.php
[2] ''	=> 'App center',//'应用中心',

//---------------------------
//admin/views/store_install.php
[3] ''	=> 'Installation',//'安装',
[5] ''	=> 'Downloading package...',//'正在下载安装中',
[13] ''	=> 'Plugin has been installed successfully',//'安装成功，',
[15] ''	=> 'Download failed. It may be network problem. Please, download and install manually.',//'下载失败，可能是服务器网络问题，请手动下载安装，',
[15] ''	=> 'Return to app center',//'返回应用中心',
[17] ''	=> 'Installation failed. Server may not support zip module. Please, download and install manually.',//'安装失败，可能是服务器不支持zip模块，请手动下载安装，',
[17] ''	=> 'Return to app center',//'返回应用中心',
[19] ''	=> 'Installation failed. Probably, directory is not wirtable.',//'安装失败，可能是应用目录不可写，',
[19] ''	=> 'Return to app center',//'返回应用中心',
[21] ''	=> 'Installation failed.',//'安装失败，',
[21] ''	=> 'Return to app center',//'返回应用中心',

//---------------------------
//admin/views/style/default/style.css
[2] Style Name: Default Style

//---------------------------
//admin/views/style/green/style.css
[2] Style Name: Green Onion

//---------------------------
//admin/views/style.php
[4] ''	=> 'Basic settings',//'基本设置',
[5] ''	=> 'SEO settings',//'SEO设置',
[6] ''	=> 'Background style',//'后台风格',
[7] ''	=> 'Personal settings',//'个人设置',
[8] ''	=> 'Settings has been saved successfully',//'设置保存成功',
[17] ''	=> 'Click to use this style',//'点击使用该风格,
[24] ''	=> 'Click to use this style',//'点击使用该风格',

//---------------------------
//admin/views/tag.php
[2] ''	=> 'Tag management',//'标签管理',
[3] ''	=> 'Tag has been removed successfully',//'删除标签成功',
[4] ''	=> 'Tag has been modified successfully',//'修改标签成功',
[5] ''	=> 'Please, select tab that you want to delete',//'请选择要删除的标签',
[19] ''	=> 'Select',//'全选',
[19] ''	=> 'Selected items',//'选中项',
[20]//'delete'	=> 'Delete',//'删除',
[23] ''	=> 'No tags yet!',//'还没有标签，写文章的时候可以给文章打标签',
[31] ''	=> 'Please, select tag that you want to delete',//'请选择要删除的标签',
[34] ''	=> 'Are you sure you want delete this tag?',//'你确定要删除所选标签吗？',

//---------------------------
//admin/views/tagedit.php
[2] ''	=> 'Tags modification',//'标签修改,
[3] ''	=> 'Tag cannot be empty',//'标签不能为空',
[11] ''	=> 'Save',//'保 存,
[12] ''	=> 'Cancel',//'取 消',

//---------------------------
//admin/views/template.php
[3] ''	=> 'Current template',//'当前模板',
[4] ''	=> 'Mounting template',//'安装模板',
[5] ''	=> 'Template has been replaced successfully',//'模板更换成功',
[8] ''	=> 'Current template',//'当前使用的模板',
[8] ''	=> 'This template has been damaged! Please choose another template.',//'已被删除或损坏，请选择其他模板。',
[19] ''	=> 'Custom top images',//'自定义顶部图片',
[26] ''	=> 'Template library',//'模板库',
[28] ''	=> 'Template has been uploaded successfully',//'模板上传成功',
[29] ''	=> 'Template has been removed successfully',//'删除模板成功',
[30] ''	=> '删除失败，请检查模板文件权限',//'删除失败，请检查模板文件权限',
[41] ''	=> 'Click to use this template',//'点击使用该模板',
[44]//'delete'	=> 'Delete',//'删除',

//---------------------------
//admin/views/template_crop.php
[2] ''	=> 'Crop image',//'裁剪图片',
[2] ''	=> 'Template hsa been replaced successfully',//'模板更换成功',
[13] ''	=> 'Crop and save',//'剪裁并保存',
[13] ''	=> 'Cancel crop',//'取消裁剪',
[13] ''	=> '(页面加载完毕后，未出现选择区域时请按下鼠标左键手动拖曳选取)',//'(页面加载完毕后，未出现选择区域时请按下鼠标左键手动拖曳选取)',

//---------------------------
//admin/views/template_install.php
[3] ''	=> 'Current template',//'当前模板',
[4] ''	=> 'Mounting template',//'安装模板',
[5] ''	=> 'Only supported for .zip files.',//'只支持zip压缩格式的模板包',
[6] ''	=> 'Upload failed. Template directory (content/templates) cannot be written.',//'上传失败，模板目录(content/templates)不可写',
[7] ''	=> '空间不支持zip模块，请按照提示手动安装模板',//'空间不支持zip模块，请按照提示手动安装模板',
[8] ''	=> '请选择一个zip模板安装包',//'请选择一个zip模板安装包',
[9] ''	=> '安装失败，模板安装包不符合标准',//'安装失败，模板安装包不符合标准',
[14] ''	=> '手动安装模板',//'手动安装模板',
[15] ''	=> '1、把解压后的模板文件夹上传到 content/templates目录下。',//'1、把解压后的模板文件夹上传到 content/templates目录下。,
[16] ''	=> '2、登录后台换模板，模板库中已经有了你刚才添加的模板，点击使用即可。',//'2、登录后台换模板，模板库中已经有了你刚才添加的模板，点击使用即可。',
[24] ''	=> 'Upload',//'上传安装',
[24] ''	=> '(Upload .zip file that contains installation package)',//'(上传一个zip压缩格式的模板安装包)',
[28] ''	=> 'Get more templates',//'获取更多模板',
[28] ''	=> 'App center &raquo;',//'应用中心&raquo;',

//---------------------------
//admin/views/template_top.php
[2] ''	=> 'Custom top images',//'自定义顶部图片',
[3] ''	=> 'Image has been replaced successfully.',//'顶部图片更换成功',
[4] ''	=> 'Image has been deleted successfully.',//'删除成功',
[5] ''	=> 'Image crop rrror',//'裁剪图片失败',
[9] ''	=> '当前未使用顶部图片或者使用中的顶部图片被删除',//'当前未使用顶部图片或者使用中的顶部图片被删除',
[14] ''	=> 'Optional images',//'可选图片',
[29] ''	=> 'Click on the image to use',//'点击使用该图片',
[34]//'delete'	=> 'Delete',//'删除',
[41] ''	=> 'Do not use the top image.',//'不使用顶部图片',
[44] ''	=> 'Do not use the top image.',//'不使用顶部图片',
[48] ''	=> 'Custom image',//'自定义图片',
[54] ''	=> 'Upload',//'上传',
[54] ''	=> '(Upload your favourite picture to top. Supported formats: jpg, png.)',//'(上传一张你喜欢的顶部图片，支持JPG、PNG格式)',

//---------------------------
//admin/views/trackback.php
[11] ''	=> '引用通告（TrackBack）管理',//'引用通告（TrackBack）管理',
[12] ''	=> '删除引用成功',//'删除引用成功',
[13] ''	=> '请选择要执行操作的引用',//'请选择要执行操作的引用',
[20] ''	=> 'Title',//'标题',
[21] ''	=> 'Source',//'来源',
[23] ''	=> 'Time',//'时间',
[38] ''	=> '还没有收到引用',//'还没有收到引用',
[42] ''	=> 'Select',//'全选',
[42] ''	=> 'Selected items',//'选中项',
[42]//'delete'	=> 'Delete',//'删除',
[43]//'have'	=> 'Have',//'有',
[43] ''	=> 'Entries',//'条引用',
[48] ''	=> 'Please, select item to operate',//'请选择要操作的引用',
[51] ''	=> 'Are you sure you want to delete it?',//'你确定要删除所选引用吗？',

//---------------------------
//admin/views/twitter.php
[2] 'twitter'	=> 'Twitter',//'微语',
[3] ''	=> 'Whisper has been sent successfully',//'发布成功',
[4] ''	=> 'Settings has been updated successfully',//'设置保存成功',
[5] ''	=> 'Whisper has been deleted successfully',//'微语删除成功',
[6] ''	=> 'Micro-blog content cannot be empty',//'微语内容不能为空',
[14] ''	=> 'Up to 140 characters',//'你还可以输入140字'',
[16] ''	=> 'Release',//'发布',
[20] ''	=> '{Image title}',//'{图片名称}',
[21] ''	=> '[Cancel]',//'[取消]',
[36] ''	=> 'View images',//'查看图片',
[43]//'reply'	=> 'Reply',//'回复',
[44]//'delete'	=> 'Delete',//'删除',
[50]//'reply'	=> 'Reply',//'回复',
[54]//'have'	=> 'Have',//'有',
[54] ''	=> 'Entry whisper',//'条微语',
[79] ''	=> 'You can enter ',//'你还可以输入',
[79] ''	=> ' words',//' 字',
[81] ''	=> 'Beyond ',//'已超出 ',
[81] ''	=> ' words',//' 字',
[94] ''	=> 'Select image',//'选择图片',
[152] ''	=> 'Upload failed!',//'上传失败！',
[163] ''	=> '{Image title}',//'{图片名称}',
[176] ''	=> 'Up to 140 characters.',//'回复长度需在140个字内',
[178] ''	=> 'The recovery already exists',//'该回复已经存在',
[188] ''	=> 'Are you sure you want to delete it?',//'你确定要删除该条回复吗？',
[193] ''	=> 'Approve',//'审核',
[203] ''	=> 'Approve',//'审核',
[212]//'hide'	=> 'Hide',//'隐藏',

//---------------------------
//admin/views/upload.php
[32] ''	=> 'Upload attachments',//'上传附件',
[33] ''	=> 'Bulk upload',//'批量上传',
[34] ''	=> 'Files library',//'附件库（',
[34] ''	=> ' )',//' ）',
[38] ''	=> 'Maximum size of single attachment',//'单个附件最大',
[38] ''	=> 'Allowed types',//'，允许类型',
[41] ''	=> 'Upload',//'上传',
[43] ''	=> 'Add attachment',//'增加附件',
[43] ''	=> '[ + ]',//'[ + ]',
[44] ''	=> 'Reduce attachments',//'减少附件',
[44] ''	=> '[ - ]',//'[ - ]',

//---------------------------
//admin/views/upload_multi.php
[23] ''	=> 'Upload attachments',//'上传附件',
[24] ''	=> 'Bulk upload',//'批量上传',
[25] ''	=> 'Files library (',//'附件库（',
[25] ''	=> ')',//'）',
[29] ''	=> 'Your browser is too old to display this feature. You cannot use the bulk upload. Please, upgrade your web browser or switch to another.',//'您正在使用的浏览器版本太低，无法使用批量上传功能。为了更好的使用emlog，建议您升级浏览器或者换用其他浏览器。',
[46] ''	=> 'Select the file',//'选择文件,

//---------------------------
//admin/views/user.php
[2] ''	=> 'User management',//'用户管理',
[3] ''	=> 'User has been removed successfully',//'删除成功',
[4] ''	=> 'User data has been modified successfully',//'修改用户资料成功',
[5] ''	=> 'User has been added successfully',//'添加用户成功',
[6] ''	=> 'Username cannot be empty',//'用户名不能为空',
[7] ''	=> 'The username already exists',//'该用户名已存在',
[8] ''	=> 'Password cannot be less than 6 characters',//'密码长度不得小于6位',
[9] ''	=> 'Enter the passwords',//'两次输入密码不一致',
[10] ''	=> 'You cannot delete Founder',//'不能删除创始人',
[11] ''	=> 'Information about Founder cannot be modified',//'不能修改创始人信息',
[19] ''	=> 'User',//'用户',
[20] ''	=> 'Description',//'描述',
[21] ''	=> 'E-mail',//'电子邮件',
[22] ''	=> 'Entry',//'文章',
[35] ''	=> 'Founder',//'创始人',
[35] ''	=> 'Administrator',//'管理员',
[35]//'user'	=> 'User',//'作者',
[36] ''	=> '(entries that need to be verfied)',//'(文章需审核)',
[39] ''	=> 'Editor',//'编辑',
[40]//'delete'	=> 'Delete',//'删除',
[42] ''	=> 'Editor',//'编辑',
[51] ''	=> 'No author yet',//'还没有添加作者',
[56]//'have'	=> 'Have',//'有',
[56] ''	=> 'Users',//'位用户',
[58] ''	=> 'Add user+',//'添加用户+',
[62] ''	=> 'Author (Contributor)',//'作者（投稿人）',
[63] ''	=> 'Administrator',//'管理员',
[66] ''	=> 'Username',//'用户名',
[67] ''	=> 'Password (more than 6 characters)',//'密码 (大于6位)',
[68] ''	=> 'Repeat password',//'重复密码',
[71] ''	=> 'Entries that do not need to be verified',//'文章不需要审核',
[72] ''	=> 'Entries that need to be verified',//'文章需要审核',
[75] ''	=> 'Add user',//'添加用户',

//---------------------------
//admin/views/useredit.php
[2] ''	=> 'Information management',//'修改作者资料',
[3] ''	=> 'Username cannot be empty',//'用户名不能为空',
[4] ''	=> 'The username already exists',//'该用户名已存在',
[5] ''	=> 'Password cannot be less than 6 characters',//'密码长度不得小于6位',
[6] ''	=> 'Enter the passwords',//'两次输入密码不一致',
[11] ''	=> 'Username',//'用户名',
[12] ''	=> 'Name',//'昵称',
[13] ''	=> 'New password (leave blank, if you do not want to modify)',//'新密码(不修改请留空)',
[14] ''	=> 'Repeat new password',//'重复新密码',
[15] ''	=> 'E-mail',//'电子邮件',
[18]//'user'	=> 'User',//'作者',
[19] ''	=> 'Administrator',//'管理员',
[24] ''	=> 'Entries that do not to be verified',//'文章不需要审核',
[25] ''	=> 'Entries that need to be verified',//'文章需要审核',
[28] ''	=> 'Personal information',//'个人描述',
[32] ''	=> 'Save',//'保 存',
[33] ''	=> 'Cancel',//取 消',

//---------------------------
//admin/views/widgets.php
[4] ''	=> 'Sidebar component managament',//'侧边栏组件管理',
[5] ''	=> 'Settings has been saved successfully',//'设置保存成功',
[12] ''	=> 'Personal information',//'个人资料',
[17] ''	=> 'Title',//'标题',
[18] ''	=> 'Change',//'更改',
[25] ''	=> 'Calendar',//'日历',
[30] ''	=> 'Title',//'标题',
[31] ''	=> 'Change',//'更改',
[38] ''	=> 'Latest whispers',//'最新微语',
[43] ''	=> 'Title',//'标题',
[45] ''	=> 'Number of latest whispers',
[46] ''	=> 'Change',//'更改',
[53] ''	=> 'Tags',//'标签',
[58] ''	=> 'Title',//'标题',
[59] ''	=> 'Change',//'更改',
[66] ''	=> 'Categories',//分类',
[71] ''	=> 'Title',//'标题',
[72] ''	=> 'Change',//'更改',
[79] ''	=> 'Archive',//'存档',
[84] ''	=> 'Title',//'标题',
[85] ''	=> 'Change',//'更改',
[92] ''	=> 'Latest comments',//'最新评论',
[97] ''	=> 'Title',//'标题',
[99] ''	=> 'Latest comments',//'首页最新评论数',
[101] ''	=> 'Summary length for latest comments',//'新近评论截取字节数',
[102] ''	=> 'Change',//'更改',
[109] ''	=> 'Latest entries',//'最新文章',
[114] ''	=> 'Title',//'标题',
[116] ''	=> 'Show latest entries',//'首页显示最新文章数',
[117] ''	=> 'Change',//'更改',
[124] ''	=> 'Popular entries',//'热门文章',
[129] ''	=> 'Title',//'标题',
[131] ''	=> 'Show popular entries',//'首页显示热门文章数',
[132] ''	=> 'Change',//'更改',
[139] ''	=> 'Random entries',//'随机文章',
[144] ''	=> 'Title',//'标题',
[146] ''	=> 'Show random entries',//'首页显示随机文章数',
[147] ''	=> 'Change',//'更改',
[154] ''	=> 'Link',//'链接',
[159] ''	=> 'Title',//'标题',
[160] ''	=> 'Change',//'更改',
[167] ''	=> 'Search',//'搜索',
[172] ''	=> 'Title',//'标题',
[173] ''	=> 'Change',//'更改',
[177] ''	=> 'Custom components',//'自定义组件',
[181] ''	=> 'Unnamed component',//'未命名组件',
[196] ''	=> 'Change',//'更改,
[197] ''	=> 'Remove component',//'删除该组件',
[203] ''	=> 'Customize new component+',//'自定义一个新的组件+',
[205] ''	=> 'Component name',//'组件名',
[207] ''	=> 'Content （html support）',//'内容 （支持html）,
[209] ''	=> 'New component',//'添加组件',
[221] ''	=> 'Sidebar',//'侧边栏',
[223] ''	=> 'Sidebar',//'侧边栏',
[235] ''	=> 'Unnamed component',//'未命名组件',
[250] ''	=> 'Sort components',//'保存组件排序',
[251] ''	=> 'Restore component settings',//'恢复组件设置到初始安装状态',

//---------------------------
//admin/widgets.php

//---------------------------
//admin/write_log.php


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<?php
//lang_comment.php:
$lang = array(

//---------------------------
//include/controller/comment_controller.php
[35] 	''	=> 'Comment error: The comments for this entry has been closed.',//'评论失败：该文章已关闭评论',
[37] 	''	=> 'Comment error: The same content already exists.',//'评论失败：已存在相同内容评论',
[39] 	''	=> 'Comment error: You must wait before sending another comment.',//'评论失败：您提交评论的速度太快了，请稍后再发表评论',
[41] 	''	=> 'Comment error: Please, enter your name.',//'评论失败：请填写姓名',
[43] 	''	=> 'Comment error: Name does not meet requirements.',//'评论失败：姓名不符合规范',
[45] 	''	=> 'Comment error: E-mail address does not meet requirements.',//'评论失败：邮件地址不符合规范',
[47] 	''	=> 'Comment error: User data cannot be the same as administrator or other users.',//'评论失败：禁止使用管理员昵称或邮箱评论',
[49] 	''	=> 'Comment error: Homepage URL is invalid.',//'评论失败：主页地址不符合规范',
[51] 	''	=> 'Comment error: Please, enter some content.',//'评论失败：请填写评论内容,
[53] 	''	=> 'Comment error: Content does not meet requirements.',//'评论失败：内容不符合规范',
[55] 	''	=> 'Comment error: Content must contain Chinese words.',//'评论失败：评论内容需包含中文',
[57] 	''	=> 'Comment error: Invalid captcha.',//'评论失败：验证码错误',

//---------------------------
//include/model/comment_model.php
[275] ''	=> 'Thank you. Your comment is waiting for approval',//'评论发表成功，请等待管理员审核',
[306] //'no_permission'	=> 'Insufficient permissions!',//'权限不足！',

//---------------------------
//m/view/comment.php
[5] ''	=> '[pending]',//'[待审]',
[9]//'delete'	=> 'Delete',//'删除',
[13] ''	=> 'An entry',//'所属文章',
[17] 'hide'	=> 'Hide',//'隐藏',
[19] ''	=> 'Approve',//'审核',
[21]//'reply'	=> 'Reply',//'回复',

//---------------------------
//m/view/reply.php
[3]//'reply'	=> 'Reply',//'回复',
[10] ''	=> 'You are currently logged in as',//'当前已登录为',
[15] ''	=> 'Name',//'昵称',
[16] ''	=> 'E-Mail adress (optional)',//'邮件地址 (选填)',
[17] ''	=> 'Homepage (optional)',//'个人主页 (选填)',
[19] ''	=> 'Content',//'内容',
[20] ''	=> 'Leave a comment',//发表评论',

);

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<?php
//lang_rss.php:
$lang = array(

//---------------------------
//rss.php
[80]  'post_encrypted'	=> '[This post has been set encrypted]',//'[该文章已设置加密]',
[89]  'read_more'	=> 'Read more',//'阅读全文',

);

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<?php
//lang_install.php:
$lang = array(

//---------------------------

//install.php

 'php5_required'	=> 'For normal functioning Emlog requires PHP5 or higher',//'您的php版本过低，请选用支持PHP5的环境安装emlog。',
 'install'		=> 'install',//'安装程序',
 'mysql_settings'	=> 'MySQL settings',//'MySQL数据库设置',
 'db_hostname'		=> 'Database Hostname',//'数据库地址',
 'db_hostname_info'	=> '(default: localhost)',//'(通常为 localhost， 不必修改)',
 'db_user'		=> 'DB user',//'数据库用户名',
 'db_password'		=> 'DB password',//'数据库密码',
 'db_name'		=> 'DB name',//'数据库名',
 'db_name_info'		=> '(The program does not automatically create a database. Please create new one)',//'(程序不会自动创建数据库，请提前创建一个空数据库或使用已有数据库)',
 'db_prefix'		=> 'DB prefix',//'数据库前缀',
 'db_prefix_info'	=> '(Typically the default, without having to modify. By the letters of the alphabet, numbers, underscores, and must end with an underscore.)',//'(通常默认即可，不必修改。由英文字母、数字、下划线组成，且必须以下划线结束)',
 'admin_settings'	=> 'Administrator account',//'管理员设置',
 'admin_name'		=> 'User name',//'登录名',
 'admin_password'	=> 'Password',//'登录密码',
 'admin_password_info'	=> '(Minimum 5 characters)',//'(不小于5位)',
 'admin_password_repeat'	=> 'Confirm password',//再次输入登录密码',
 'install_emlog'	=> 'Install emlog!',//'开始安装emlog',
 'db_prefix_empty'	=> 'Database prefix can not be empty!',//'数据库前缀不能为空!',
 'db_prefix_invalid'	=> 'Database prefix is incorrect!',//'数据库前缀格式错误!',
 'username_password_empty'	=> 'Username and password can not be empty!',//'登录名和密码不能为空!',
 'password_short'	=> 'Password can not be less than 5 characters',//'登录密码不得小于5位',
 'password_not_equal'	=> 'Two passwords are not equal',//'两次输入的密码不一致',
 'already_installed'	=> 'It seems the Emlog is already installed! Continue this process will overwrite the original data. Are you sure?',//'你的emlog看起来已经安装过了。继续安装将会覆盖原有数据，确定要继续吗？',
 'continue'		=> 'Continue&raquo;',//'继续&raquo;',
 'return'		=> '&laquo;Return back',//'&laquo;点击返回',
 'config_not_writable'	=> 'Configuration file (config.php) is not writable. If you are using a Unix / Linux hosts, modify the file permissions to 777. If you are using a Windows host, please contact the administrator.',//'配置文件(config.php)不可写。如果您使用的是Unix/Linux主机，请修改该文件的权限为777。如果您使用的是Windows主机，请联系管理员，将此文件设为可写',
 'cache_not_writable'	=> 'Cache is not writable. If you are using a Unix / Linux host, modify the permissions of all files in the directory (content/cache) to 777.',//'缓存文件不可写。如果您使用的是Unix/Linux主机，请修改缓存目录 (content/cache) 下所有文件的权限为777。如果您使用的是Windows主机，请联系管理员，将该目录下所有文件设为可写',
 'emlog_welcome'	=> 'Welcome to emlog',//'欢迎使用emlog',
 'emlog_install_congratulation'	=> 'Congratulations, you have successfully installed the emlog. The first entry is ready. Just edit or delete it and start a blog!',//'恭喜您成功安装了emlog，这是系统自动生成的演示文章。编辑或者删除它，然后开始您的创作吧！',
 'my_blog'		=> 'My blog',//'点滴记忆',
 'emlog_powered'	=> 'Powered by emlog',//'使用emlog搭建的站点',
 'emlog_official_site'	=> 'Official emlog website',//'emlog官方主页',
 'home'			=> 'Home',//'首页',
 'twitter'		=> 'Twitter',//'微语',
 'login'		=> 'Login',//'登录',
 'test_tweet'		=> 'I heard some whispers last night... :)',//'使用微语记录您身边的新鲜事',
 'emlog_installed'	=> 'Congratulations, your blog is ready to use!',//'恭喜，安装成功！',
 'emlog_installed_info'	=> 'Now you can start to create your content. It\'s really simple!',//'您的emlog已经安装好了，现在可以开始您的创作了，就这么简单!',
 'user_name'		=> 'User name',//'用户名',
 'password'		=> 'Password',//'密 码',
 'password_entered'	=> 'you have created a two seconds ago',//'您刚才设定的密码',
 'delete_install'	=> 'Warning! Please delete the installation file install.php',//'警告：请手动删除根目录下安装文件：install.php',
 'go_to_front'		=> 'Visit Blog',//'访问首页',
 'go_to_admincp'	=> 'Go to Administration Control Panel',//'登录后台',

//---------------------------------------
//include/lib/mysql.php

 'db_not_found'		=> 'Database connection failed. The database you filled in was not found.',//'连接数据库失败，未找到您填写的数据库',
 'db_sql_error'		=> 'SQL statement execution error',//'SQL语句执行错误',
);

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

<?php
//lang_???.php:
$lang = array(

//---------------------------
//content/plugins/tips/tips.php
[15] ''	=> 'You can upload some attachments in this entry.',//'你可以在文章中上传多个附件',
[16] ''	=> '试试给你的EM后台换个风格吧，就在设置里面',//'试试给你的EM后台换个风格吧，就在设置里面',
[17] ''	=> 'Emlog supports flexible label (tag) function.',//'emlog支持灵活的标签(tag)功能',
[18] ''	=> '在撰写文章的时候你可以使用Tab键方便的缩进内容',//'在撰写文章的时候你可以使用Tab键方便的缩进内容',
[19] ''	=> '你可以为你的文章写一段漂亮的摘要，这样仅让摘要显示在首页并出现阅读全文链接',//'你可以为你的文章写一段漂亮的摘要，这样仅让摘要显示在首页并出现阅读全文链接',
[20] ''	=> '为防文章丢失，emlog会在你书写文章的时候为你自动保存它们',//'为防文章丢失，emlog会在你书写文章的时候为你自动保存它们',
[21] ''	=> '你可以在文章中插入flash格式的多媒体文件',//'你可以在文章中插入flash格式的多媒体文件',
[22] ''	=> '不一样的心情，文章表情图标为您传达',//'不一样的心情，文章表情图标为您传达',
[23] ''	=> '你可以把你未写完的文章保存到草稿箱里，等下次有时间的时候再写',//'你可以把你未写完的文章保存到草稿箱里，等下次有时间的时候再写',
[24] ''	=> 'emlog会把太大的图片附件自动生产缩略图，从而加快页面加载速度',//'emlog会把太大的图片附件自动生产缩略图，从而加快页面加载速度',
[25] ''	=> '请关注后台首页的 官方信息 栏目，这里有最新的emlog动态',//'请关注后台首页的 官方信息 栏目，这里有最新的emlog动态',
[26] ''	=> '你可以把图片附件嵌入到内容中，让你的文章图文并茂',//'你可以把图片附件嵌入到内容中，让你的文章图文并茂',
[27] ''	=> '你可以在写文章的时候为文章设置访问密码，只让你授予密码的人访问',//'你可以在写文章的时候为文章设置访问密码，只让你授予密码的人访问',
[28] ''	=> 'emlog支持多人联合撰写',//'emlog支持多人联合撰写',
[29] ''	=> 'emlog支持自建页面，并且可以上传照片，为自己做一个图文并茂的自我介绍页吧',//'emlog支持自建页面，并且可以上传照片，为自己做一个图文并茂的自我介绍页吧',
[30] ''	=> 'Create a review page that allow you to create simple message board.',//'新建一个允许发表评论的页面，你会发现其实它还是一个简单的留言板',
[31] ''	=> 'Please, delete your installation file install.php .',//'检查你的站点目录下是否存在安装文件：install.php，有的话请删除它',
[32] ''	=> 'Timely upgrade your browser for a better experience with emlog.',//'及时升级浏览器，更好的体验emlog',
[33] ''	=> 'Did you backup your files today?',//'今天你备份数据了吗？',
[34] ''	=> 'From tomorrow you will be happy person. Horses, firewood and traveling around the world!',//'从明天起，做一个幸福的人。喂马，砍柴，周游世界',

//---------------------------
//content/templates/default/404.php
[11] ''	=> 'Error - page not found.',//'错误提示-页面未找到',
[40] ''	=> 'Sorry, the page that you requested does not exist.',//'抱歉，你所请求的页面不存在！',
[41] ''	=> '&laquo; Click here to return',//'&laquo;点击返回',

//---------------------------
//content/templates/default/echo_log.php
'' ToDo: 'Y-n-j G:i'	=> 'Y-m-d H:i'
[10]//'user'	=> 'User',//'作者',
[10]//'post_time'	=> 'Posted on',//'发布于',

//---------------------------
//content/templates/default/footer.php
[10] ''	=> 'Powered by',
[10] ''	=> 'Powered by Emlog',//'采用emlog系统',

//---------------------------
//content/templates/default/header.php

//---------------------------
//content/templates/default/log_list.php
[16]//'user'	=> 'User',//'作者',
[16]//'post_time'	=> 'Posted on',//'发布于',
[23] ''	=> 'Comment',//'评论',
[24] ''	=> 'Browse',//'浏览',
[31] ''	=> 'Not found.',//'未找到',
[32] ''	=> 'Sorry, no results found.',//'抱歉，没有符合您查询条件的结果。',

//---------------------------
//content/templates/default/module.php
[46] ''	=> 'Entries',//'篇文章',
[65] ''	=> 'Subscribe this category',//'订阅该分类',
[75] ''	=> 'Subscribe this category',//'订阅该分类',
[95] ''	=> 'View images',//'查看图片',
[99] ''	=> 'More &raquo;',//'更多&raquo;',
[232] ''	=> 'Site management',//'管理站点',
[233]//'logout'			=> 'Logout',//'退出',
[257] ''	=> 'Top entries',//'置顶文章',
[264] ''	=> 'Editor',//'编辑',
[275] ''	=> 'Category',//'分类',
[284] ''	=> 'Tag',//'标签',
[324] ''	=> 'Comment',//'评论',
[338]//'reply'	=> 'Reply',//'回复',
[361]//'reply'	=> 'Reply',//'回复',
[373] ''	=> 'Cancel reply',//'取消回复',
[374] ''	=> 'Leave a comment',//'发表评论',
[380] ''	=> 'Name',//'昵称',
[384] ''	=> 'E-mail address (optional)',//'邮件地址 (选填)',
[388] ''	=> 'Homepage (optional)',//'个人主页 (选填)',
[392] ''	=> 'Leave a comment',//'发表评论',

//---------------------------
//content/templates/default/page.php

//---------------------------
//content/templates/default/side.php
[34] ''	=> 'RSS Subscription',//'RSS订阅',
[34] ''	=> 'RSS Subscription',//'订阅Rss',

//---------------------------
//content/templates/default/t.php
[18] ''	=> 'View images',//'查看图片',
[25]//'reply'	=> 'Reply',//'回复',
[35] ''	=> 'Username',//'昵称',
[36] ''	=> 'Captcha',//'验证码',
[38]//'reply'	=> 'Reply',//'回复',

//---------------------------
//include/controller/author_controller.php

//---------------------------
//include/controller/log_controller.php

//---------------------------
//include/controller/plugin_controller.php

//---------------------------
//include/controller/record_controller.php

//---------------------------
//include/controller/search_controller.php

//---------------------------
//include/controller/sort_controller.php

//---------------------------
//include/controller/tag_controller.php

//---------------------------
//include/lib/cache.php
[392] 'date_short_format'	=> 'm.Y',//'Y年n月',
[475] ''	=> '读取缓存失败。如果您使用的是Unix/Linux主机，请修改缓存目录 (content/cache) 下所有文件的权限为777。如果您使用的是Windows主机，请联系管理员，将该目录下所有文件设为可写',//'读取缓存失败。如果您使用的是Unix/Linux主机，请修改缓存目录 (content/cache) 下所有文件的权限为777。如果您使用的是Windows主机，请联系管理员，将该目录下所有文件设为可写',
[476] ''	=> 'The cache directory (content/cache) is not writable.',//'写入缓存失败，缓存目录 (content/cache) 不可写',

//---------------------------
//include/lib/calendar.php
[73] ''	=> 'Monday',//'一',
[73] ''	=> 'Tuesday',//'二',
[73] ''	=> 'Wednesday',//'三',
[73] ''	=> 'Thursday',//'四',
[73] ''	=> 'Friday',//'五',
[73] ''	=> 'Saturday',//'六',
[73] ''	=> 'Sunday',//'日',

//---------------------------
//include/lib/checkcode.php

//---------------------------
//include/lib/dispatcher.php

//---------------------------
//include/lib/function.base.php
[16] ''	=> ' Failed to load.',//'加载失败。',
[208] ''	=> ' Byte',//'字节',
[244]//'home'	=> 'Home',//'首页',
[246] ''	=> 'End',//'尾页',
[291] ''	=> 'Read more &gt;&gt;',//'阅读全文&gt;&gt;',
[294] ''	=> 'Read more &gt;&gt;',//'阅读全文&gt;&gt;',
[326] ''	=> ' seconds ago.',//'秒前',
[328] ''	=> ' minutes ago.',//'分钟前',
[331] ''	=> '~ {$hover} ago.',//'约 {$hover} 小时前',
[371] ''	=> 'File size exceeds ' . ini_get('upload_max_filesize') . ' limit.',//'文件大小超过系统 ' . ini_get('upload_max_filesize') . ' 限制',
[374] ''	=> 'Upload failed. Error code: ',//'上传文件失败,错误码: ',
[377] ''	=> 'This file type is not supported.',//'错误的文件类型',
[381] ''	=> 'File size exceeds {$ret} limit.',//'文件大小超出 {$ret} 的限制',
[384] ''	=> 'Failed to create file upload directory.',//创建文件上传目录失败',
[387] ''	=> 'Upload failed. Directory (content/uploadfile) cannot be written.',//'上传失败。文件上传目录(content/uploadfile)不可写',
[856] ''	=> 'Sorry, the page that you requested does not exist!',//'抱歉，你所请求的页面不存在！',
[868] ''	=> 'Message',//'提示信息',
[900] ''	=> '&laquo; click to return',//'点击返回',
[930] '[耶]'=>'0.gif', '[呵呵]'=>'1.gif', '[悲伤]'=>'2.gif', '[抓狂]'=>'3.gif', '[衰]'=>'4.gif', '[花心]'=>'5.gif', '[哼]'=>'6.gif', '[泪]'=>'7.gif', '[害羞]'=>'8.gif', '[酷]'=>'9.gif', '[晕]'=>'10.gif', '[挤眼]'=>'11.gif', '[鬼脸]'=>'12.gif', '[汗]'=>'13.gif', '[吃惊]'=>'14.gif', '[发呆]'=>'15.gif', '[闭嘴]'=>'16.gif', '[撇嘴]'=>'17.gif', '[疑问]'=>'18.gif', '[睡觉]'=>'19.gif', '[NO]'=>'20.gif', '[大哭]'=>'21.gif', '[爱你]'=>'22.gif', '[嘻嘻]'=>'23.gif', '[生病]'=>'24.gif', '[偷笑]'=>'25.gif', '[思考]'=>'26.gif', '[玫瑰]'=>'27.gif', '[心]'=>'28.gif', '[伤心]'=>'29.gif', '[咖啡]'=>'30.gif', '[音乐]'=>'31.gif', '[下雨]'=>'32.gif', '[晴天]'=>'33.gif', '[星星]'=>'34.gif', '[月亮]'=>'35.gif');
//[930] '[耶]'=>'0.gif', '[呵呵]'=>'1.gif', '[悲伤]'=>'2.gif', '[抓狂]'=>'3.gif', '[衰]'=>'4.gif', '[花心]'=>'5.gif', '[哼]'=>'6.gif', '[泪]'=>'7.gif', '[害羞]'=>'8.gif', '[酷]'=>'9.gif', '[晕]'=>'10.gif', '[挤眼]'=>'11.gif', '[鬼脸]'=>'12.gif', '[汗]'=>'13.gif', '[吃惊]'=>'14.gif', '[发呆]'=>'15.gif', '[闭嘴]'=>'16.gif', '[撇嘴]'=>'17.gif', '[疑问]'=>'18.gif', '[睡觉]'=>'19.gif', '[NO]'=>'20.gif', '[大哭]'=>'21.gif', '[爱你]'=>'22.gif', '[嘻嘻]'=>'23.gif', '[生病]'=>'24.gif', '[偷笑]'=>'25.gif', '[思考]'=>'26.gif', '[玫瑰]'=>'27.gif', '[心]'=>'28.gif', '[伤心]'=>'29.gif', '[咖啡]'=>'30.gif', '[音乐]'=>'31.gif', '[下雨]'=>'32.gif', '[晴天]'=>'33.gif', '[星星]'=>'34.gif', '[月亮]'=>'35.gif');

//---------------------------
//include/lib/loginauth.php
[70] ''	=> 'Captcha',//'验证码',
[78] ''	=> 'Captcha error. Please, re-enter.',//'验证错误，请重新输入',
[81] ''	=> 'Wrong username. Please, re-enter.',//'用户名错误，请重新输入',
[84] ''	=> 'Wrong password. Please, re-enter.',//'密码错误，请重新输入',

//---------------------------
//include/lib/mysql.php
[43] ''	=> '服务器PHP不支持MySql数据库',//服务器PHP不支持MySql数据库',
[48] ''	=> 'Database connection error: The database server is unavailable.',//'连接数据库失败，数据库地址错误或者数据库服务器不可用',
[51] ''	=> 'Database connection error: The database port is invalid.',//'连接数据库失败，数据库端口错误',
[54] ''	=> 'Database connection error: The database server is unavailable.',//'连接数据库失败，数据库服务器不可用',
[57] ''	=> 'Database connection error: Wrong username or password.',//'连接数据库失败，数据库用户名或密码错误',
[60] ''	=> 'Database connection error: Please, check database information.',//'连接数据库失败，请检查数据库信息。错误编号',
[67] ''	=> 'Database connection error: Could not connect to mysql.',//'连接数据库失败，未找到您填写的数据库',
[95] ''	=> 'SQL execution error.',//SQL语句执行错误',

//---------------------------
//include/lib/option.php
[152] 'blogger'		=> 'Personal information',//'个人资料',
[153] 'calendar'	=> 'Calendar',//'日历',
[154] 'twitter'		=> 'Twitter',//'最新微语',
[155] 'tag'		=> 'Tag',//'存档',
[156] 'sort'		=> 'Category',//'存档',
[157] 'archive'		=> 'Archive',//'存档',
[158] 'newcomm'		=> 'Latest comments',//'最新文章',
[159] 'newlog'		=> 'Latest entries',//'最新文章',
[160] 'random_log'	=> 'Random entry',//'随机文章',
[161] 'hotlog'		=> 'Popular entries',//'热门文章',
[162] 'link'		=> 'Link',//'链接',
[163] 'search'		=> 'Search',//'搜索',
[164] 'custom_text'	=> 'Custom components'//'自定义组件',

//---------------------------
//include/lib/url.php

//---------------------------
//include/lib/view.php
[10] ''	=> 'The current template has been deleted or corrupted. Please please login as administrator to replace other template.',//'当前使用的模板已被删除或损坏，请登录后台更换其他模板。',

//---------------------------
//include/model/link_model.php

//---------------------------
//include/model/log_model.php
[84] //'no_permission'	=> 'Insufficient permissions!',//'权限不足！',
[151] ''	=> 'Untitled',//'无标题',
[183] ''	=> '[This entry has been protected. Click on title and enter the password to access this page.]',//'[该文章已设置加密，请点击标题输入密码访问]',
[186] ''	=> 'Read more &gt;&gt;',//'阅读全文&gt;&gt;',
[208] ''	=> 'Untitled',//'无标题',
[227] //'no_permission'	=> 'Insufficient permissions!',//'权限不足！',
[258] //'no_permission'	=> 'Insufficient permissions!',//'权限不足！', './');
[418] ''	=> 'Please enter password to access this page.',//'请输入该文章的访问密码',
[419] ''	=> 'Enter..',//'进入',
[420] ''	=> '&laquo; Back to home',//'&laquo;返回首页',

//---------------------------
//include/model/navi_model.php

//---------------------------
//include/model/plugin_model.php

//---------------------------
//include/model/reply_model.php

//---------------------------
//include/model/sort_model.php
[67] 'Unclassified',//'未分类',

//---------------------------
//include/model/tag_model.php
[67] DO NOT TRANSLATE!!!		$tag = !empty($tagStr) ? preg_split ("/[,\s]|(，)/", $tagStr) : array();
[88] DO NOT TRANSLATE!!!		$tag = !empty($tagStr) ? preg_split ("/[,\s]|(，)/", $tagStr) : array();

//---------------------------
//include/model/trackback_model.php

//---------------------------
//include/model/twitter_model.php
[82]//'no_permission'	=> 'Insufficient permissions!',//'权限不足！', './');

//---------------------------
//include/model/user_model.php

//---------------------------
//index.php

//---------------------------
//init.php

//---------------------------
//m/index.php
[19] ''	=> 'Mobile version of the site is not available.',//'该站点手机版已关闭！',
[47] ''	=> 'The entry does not exist.',//'不存在该条目',
[165] ''	=> 'Comment error: The comments for this entry has been closed.',//'评论失败：该文章已关闭评论',
[167] ''	=> 'Comment error: The same content already exists.',//'评论失败：已存在相同内容评论',
[169] ''	=> 'Comment error: You must wait before sending another comment.',//'评论失败：您提交评论的速度太快了，请稍后再发表评论',
[171] ''	=> 'Comment error: Name does not meet requirements.',//'评论失败：姓名不符合规范',
[173] ''	=> 'Comment error: E-mail address does not meet requirements.',//'评论失败：邮件地址不符合规范',
[175] ''	=> 'Comment error: User data cannot be the same as administrator or other users.',//'评论失败：禁止使用管理员昵称或邮箱评论',
[177] ''	=> 'Comment error: Content does not meet requirements.',//'评论失败：内容不符合规范',
[179] ''	=> 'Comment error: Content must contain Chinese words.',//'评论失败：评论内容需包含中文',
[181] ''	=> 'Comment error: Invalid captcha.',//'评论失败：验证码错误',
[209] ''	=> 'Thank you. Your comment is waiting for approval.',//'评论发表成功，请等待管理员审核',
[258] ''	=> 'Parameter error',//'参数错误',
[288] ''	=> 'Share images',//'分享图片',
[328] ''	=> 'Captcha',//'验证码',

//---------------------------
//m/view/header.php
[34]//'home'	=> 'Home',//'首页',
[36]//'twitter'	=> 'Twitter',//'微语',
[38] ''	=> 'Comment',//'评论',
[40]//'post_write'	=> 'Write post',//'写文章',
[41]//'logout'			=> 'Logout',//'退出',
[43] ''	=> 'Login',//'登录',

//---------------------------
//m/view/log.php
[7] ''	=> 'Comment',//'评论',
[7] ''	=> 'Reads',//'阅读',
[9] ''	=> 'Editor',//'编辑',

//---------------------------
//m/view/logauth.php
[3] ''	=> 'This article requires a password to access. Please, enter the password.',//'该文章需要密码才能访问，请输入密码',
[5] ''	=> 'Determine',//'确定',
[6] ''	=> '&laquo; Back to home',//'&laquo;返回首页',

//---------------------------
//m/view/login.php
[4] ''	=> 'Name',//'用户名',
[6] ''	=> 'Password',//'密码',
[9] ''	=> 'Login',//'登 录',

//---------------------------
//m/view/msg.php
[4] ''	=> 'Return',//'返回',

//---------------------------
//m/view/single.php
[6]//'delete'	=> 'Delete',//'删除',
[10] ''	=> 'Comment',//'评论',
[18]//'reply'	=> 'Reply',//'回复',
[24] ''	=> 'Leave a comment',//'发表评论',
[28] ''	=> 'You are logged as',//'当前已登录为',
[30] ''	=> 'Name',//'昵称',
[31] ''	=> 'E-mail adress (optional)'//'邮件地址 (选填)',
[32] ''	=> 'Homepage (optional)',//'个人主页 (选填)',
[34] ''	=> 'Content',//'内容',
[35] ''	=> 'Leave a comment',//'发表评论',

//---------------------------
//m/view/twitter.php
[5] ''	=> 'Micro-blog content',//'微语内容',
[7] ''	=> 'Select an image to upload',//'选择要上传的图片',
[9] ''	=> 'Release',//'发布',
[14] ''	=> 'View images',//'查看图片',
[20]//'delete'	=> 'Delete',//'删除',

//---------------------------
//m/view/write.php
[4] ''	=> 'Title',//'标题',
[5] ''	=> 'Category',//分类',
[8]//'category_select'	=> 'Select Category...',//'选择分类...',
[16] ''	=> 'Content',//'内容',
[17] ''	=> 'Summary',//'摘要',
[18] ''	=> 'Tags',//'标签',
[22]//'post_publish'	=> 'Publish Post',//'发布文章',

//---------------------------
//t/index.php
[14] ''	=> '抱歉，微语未开启前台访问！',//'抱歉，微语未开启前台访问！',
[53]//'reply'	=> 'Reply',//'回复',
[61] ''	=> 'No replies',//'还没有回复！',
[126]//'reply'	=> 'Reply',//'回复',

//---------------------------
//tb.php

//---------------------------
//wlwmanifest.xml
[10] ''	=> 'View website',//'查看网站',
[11] ''	=> 'Manage',//'后台管理',
[26] ''	=> 'Editorial review',//'编辑评论',

//---------------------------
//xmlrpc.php
[58] ''	=> '提示:站点XMLRPC服务未开启.',//'提示:站点XMLRPC服务未开启.',
[61] ''	=> '错误:XML-RPC服务器只能接受POST数据',//'错误:XML-RPC服务器只能接受POST数据',
[70] ''	=> 'Error: Data cannot be empty.',//'错误:提交数据内容为空',
[288] ''	=> 'Sorry, you have no access to artcile.',//'对不起,您访问的文章不存在',
[444] ''	=> 'No articles.',//'没有文章',
[459] ''	=> 'File error.',//'文件错误',
[470] ''	=> 'File name error.',//'文件名错误',
[475] ''	=> 'File type error.',//'文件类型错误',
[485] ''	=> 'Failed to create new file.',//'创建文件上传目录失败',
[492] ''	=> 'Upload failed. Directory cannot be updated (content/uploadfile).',//'上传失败。文件上传目录(content/uploadfile)不可写',
[498] ''	=> 'Files cannot be saved',//'文件无法写入',
[598] ''	=> 'Username password error',//'用户名密码错误',

