<?php

$lang = array(

//---------------------------
//admin/navbar.php
[101] 'addres_generated'	=> 'The address generated by the navigation system, can not be modified',//'该导航地址由系统生成，无法修改',

//---------------------------
//admin/views/navbar.php
[2] 'nav_manage'	=> 'Navigation management',//'导航管理',
[3]// 'category_update_ok'	=> 'Category updated successfully',//'排序更新成功',
[4] 'nav_delete_ok'	=> 'Navigation deleted successfully',//'删除导航成功',
[5] 'nav_edit_ok'	=> 'Navigation modifyied successfully',//'修改导航成功',
[6] 'nav_add_ok'	=> 'Navigation added successfully',//'添加导航成功',
[7] 'nav_name_url_empty'	=> 'Navigation name and address can not be empty',//'导航名称和地址不能为空',
[8] 'nav_no_order'		=> 'There is no order of navigation',//'没有可排序的导航',
[9] 'nav_default_nodelete'	=> 'You can not delete the default navigation',//'默认导航不能删除',
[10] 'select_category'	=> 'Please select the category you want to add',//'请选择要添加的分类',
[11] 'select_page'	=> 'Please select the page you want to add',//'请选择要添加的页面',
[12] 'nav_url_invalid'	=> 'Invalid navigation address format (must include the http prefix, etc.)',//'导航地址格式错误(需包含http等前缀)',
[19]// 'id'		=> 'ID',//'序号',
[20]// 'navigation'	=> 'Navigation',//'导航',
[21] 'type'		=> 'Type',//'类型',
[22]// 'status'		=> 'Status',//'状态',
[23] 'view'		=> 'View',//'查看',
[24]// 'address'	=> 'Address',//'地址',
[37] 'system'		=> 'System',//'系统',
[40]// 'category'	=> 'Category',//'分类',
[43] 'pages'		=> 'Pages',//'页面',
[46] 'custom'		=> 'Custom',//'自定',
[53] 'nav_edit'		=> 'Edit navigation',//'编辑导航',
[57] 'nav_hide_click'	=> 'Click to hide navigation',//'点击隐藏导航',
[57]// 'show'		=> 'Show',//'显示',
[59] 'nav_show_click'	=> 'Click to show navigation',//'点击显示导航',
[59]// 'hide'		=> 'Hide',//'隐藏',
[68]// 'edit'		=> 'Edit',//'编辑',
[70]// 'delete'		=> 'Delete',//'删除',
[75] 'nav_no'		=> 'Has not yet added navigation',//'还没有添加导航',
[79]// 'order_change'	=> 'Change order',//'改变排序',
[84] 'nav_add_custom'	=> 'Add custom navigation',//'添加自定义导航','添加自定义导航+',
[86]// 'id'		=> 'ID',//'序号',,
[87] 'nav_name'		=> 'Navigation Name',//'导航名称',
[89] 'nav_url_http'	=> Address (with http),//'地址(带http)',
[90] 'open_new_win'	=> 'Open in new window',//'在新窗口打开',
[91] 'add'		=> 'Add',//'添加',
[97] 'nav_add_category'	=> 'Add category navigation',//'添加分类到导航',//'添加分类到导航+',
[108]// 'add'		=> 'Add',//'添加',
[110] 'no_categories'	=> 'No categories',//'还没有分',//'还没有分类',//'还没有分,',
[110] 'new_category'	=> 'New Category',//'新建分类',
[117] 'nav_page_add'	=> 'Add pages to the navigation',//'添加页面到导航',//'添加页面到导航+',
[128]// 'add'		=> 'Add',//'添加',
[130] 'pages_no'	=> 'No pages',//'还没页面',//'还没页面，','还没页面,',
[130]// 'add_page'	=> 'Add page',//'新建页面',

//---------------------------
//admin/views/naviedit.php
[2] 'nav_modify'	=> 'Modify navigation',//'修改导航',
[6]// 'nav_name'	=> 'Navigation Name',//'导航名称',
[8] 'nav_address'	=> 'Navigation address',//'导航地址，','导航地址,'
[9]// 'open_new_win'	=> 'Open in new window',//'在新窗口打开',
[13]// 'save'		=> 'Save',//'保 存',
[14]// 'cancel'		=> 'Cancel',//'取 消',


);
