/*
 *Author:奇遇
 *Url:http://www.qiyuuu.com/
 */
var te=t1=t2=mX=mY=mC=newcmt=0,mS=[];
$(function(){$(".title-list ul").children("li").each(function(a){$(this).mousemove(function(){$(".content-list").each(function(b){b==a?$(this).slideDown():$(this).slideUp()})})});$(".logo").click(function(){if($(this).css("left")=="20px")var a=($.browser.msie?document.compatMode=="CSS1Compat"?document.documentElement.clientWidth:document.body.clientWidth:self.innerWidth)-178,b=["\u6211\u8dd1\uff5e","\u6211\u8dd1\u6765\u53f3\u8fb9","\u54fc\u5527\u7684\uff0c\u522b\u73a9\u6211!","\u563f\u563f\uff0c\u4f60\u6293\u4e0d\u5230\u6211",
"\u6765\u5440\u6765\u5440\uff5e"];else a=20,b=["\u6211\u8dd1\uff5e","\u6211\u8dd1\u6765\u5de6\u8fb9","\u54fc\u5527\u7684\uff0c\u522b\u73a9\u6211!","\u563f\u563f\uff0c\u4f60\u6293\u4e0d\u5230\u6211","\u6765\u5440\u6765\u5440\uff5e"];var c=Math.floor(Math.random()*b.length);$(this).animate({left:a+"px"},1E3,function(){showMessage(b[c]);setTimeout(hideMessage,5E3);$.cookie("logo-position",$(this).css("left"),{expires:365})})});movingEyes.init();$(document).mousemove(function(a){if(te==0)te=1,t1=
a.timeStamp,mX=a.clientX,mY=a.clientY;t2=a.timeStamp;var b=t2-t1;if(!(b<100)&&$("#message").css("display")=="none"){te=0;var c=a.clientX-mX,a=a.clientY-mY,d=Math.sqrt(Math.pow(c,2)+Math.pow(a,2)),g=Math.atan(a/c),g=$(".logo").css("left")=="20px"?-Math.atan(a/c):Math.atan(a/c);d*=Math.cos(g-Math.PI/5);mS[mS.length]=[d/b];mS.length>5&&mS.shift();eval(mS.join("+")+"/"+mS.length)>10?(b=["\u6211\u6655\u4e86@@","\u522b\u6643\u4e86@@",
"\u54fc\u5527\u7684><","\u9f20\u6807\u574f\u4e86\uff1f\u6643\u90a3\u4e48\u5feb@@","\u5582\uff0c\u90a3\u8c01\uff0c\u4e70\u4e2a\u65b0\u9f20\u6807\u5427"],showMessage(b[Math.floor(Math.random()*b.length)]),mS=[]):setTimeout(hideMessage,5E3)}});$(document).keypress(function(a){(a.ctrlKey&&a.which==13||a.which==10)&&$("#comment_submit").click()});$("#comment,input[name=comname],input[name=commail],input[name=comurl],#comment_submit,#smiles").hover(function(){mC=1},function(){mC=
0});$("#comment").click(function(){showMessage("\u5c3d\u60c5\u6325\u6d12\u4f60\u7684\u6587\u5b57\u5427\uff5e")});$("#comment,input[name=comname],input[name=commail],input[name=comurl]").blur(function(){mC||resetLogo()}).click(function(){scrollLogo(this)}).keyup(function(){var a=$(this).attr("name");eval("checkInfo.ck"+a+"(this);")});$("#smiles img").click(function(){var a=$(this).attr("id");$("#comment").insertAtCaret("|"+a+"|")}).mousemove(function(){scrollLogo("#smiles");showMessage('<img src="'+
$(this).attr("src")+'" height="50" width="50" />')});$("#smiles").hover(function(){},function(){hideMessage()})});
var checkInfo={ckcomname:function(a){var b=$.trim($(a).val());if(b=="")return showMessage("\u6635\u79f0\u4e0d\u80fd\u4e3a\u7a7a\u54e6\uff5e"),scrollLogo(a),!1;if(b.length>30)return showMessage("\u6635\u79f0\u592a\u957f\u4e86\u5566\uff5e"),scrollLogo(a),!1;$("#message").fadeOut("fast");return!0},ckcommail:function(a){var b=$.trim($(a).val());if(b!=""&&!checkEmail(b))return showMessage("\u90ae\u7bb1\u683c\u5f0f\u9519\u8bef\u4e86@@"),scrollLogo(a),!1;$("#message").fadeOut("fast");return!0},ckcomurl:function(a){return 1;},ckcomment:function(a){var b=$.trim($(a).val());if(b=="")return showMessage("\u7a7a\u8bc4\u8bba\u53ef\u4e0d\u80fd\u53d1\u54e6\uff5e"),scrollLogo(a),!1;if(b.length>2E3)return showMessage("\u592a\u957f\u4e86\u5566\uff0c\u5206\u6bb5\u5199\u5427:)"),
scrollLogo(a),!1;$("#message").fadeOut("fast");return!0}},movingEyes={MAX_DIST:11,EYE_RADIUS:15,PUPIL_RADIUS:5,pupils:[$("#movingEye1"),$("#movingEye2")],init:function(){$(document).mousemove(movingEyes.moveEyes)},moveEyes:function(a){if(!a)a=window.event;for(var b=movingEyes,c=0;c<b.pupils.length;c++){var d=b.pupils[c],g=d.parent().offset().left+b.EYE_RADIUS,f=d.parent().offset().top+b.EYE_RADIUS,h=0,e=0;typeof window.pageXOffset=="number"?(h=window.pageXOffset,e=window.pageYOffset):(h=document.documentElement.scrollLeft,
e=document.documentElement.scrollTop);g=a.clientX+h-g;f=a.clientY+e-f;e=Math.sqrt(Math.pow(g,2)+Math.pow(f,2));e>b.MAX_DIST&&(e=b.MAX_DIST/e,g*=e,f*=e);d.css({left:parseInt(g+b.EYE_RADIUS-b.PUPIL_RADIUS)+"px",top:parseInt(f+b.EYE_RADIUS-b.PUPIL_RADIUS)+"px"})}}};
function commentSubmit(){var a=$("input[name=comname]"),b=$("input[name=commail]"),c=$("input[name=comurl]"),d=$("#comment");if(!checkInfo.ckcomname(a))return a.focus(),!1;if(!checkInfo.ckcommail(b))return b.focus(),!1;if(!checkInfo.ckcomurl(c))return c.focus(),!1;if(!checkInfo.ckcomment(d))return d.focus(),!1;var g=$("input[name=gid]").val(),f=$("input[name=pid]").val(),a=$.trim(a.val()),b=$.trim(b.val()),c=$.trim(c.val()),d=$.trim(d.val()),c="gid="+g+"&pid="+f+"&comname="+encodeURIComponent(a)+
"&commail="+encodeURIComponent(b)+"&comurl="+encodeURIComponent(c)+"&comment="+encodeURIComponent(d);$("#comment_submit,#comment").attr("disabled","disabled");showMessage("\u8bc4\u8bba\u63d0\u4ea4\u4e2d\u2026");scrollLogo("#comment");d=d.replace(/\|ali(\d+)\|/ig,'<img src="/content/templates/greywonder/images/ali/$1.gif" width="50" height="50" />');$.post("/?action=addcom",c,function(c){var c=$.trim(c),e=/<div class=\"main\">[\r\n]*<p>(.*?)<\/p>/i;e.test(c)?(c=c.match(e)[1],showMessage(c),scrollLogo("#comment")):
(showMessage("\u8bc4\u8bba\u5df2\u7ecf\u53d1\u5e03\u5566\uff5e"),newcmt++,$.getScript("./jquery.md5.js"),c=$.md5(b),d=d.replace(/\|ali(\d+)\|/ig,'<img src="/content/templates/greywonder/images/ali/$1.gif" width="50" height="50" />'),c='<li class="comment new" id="newcomment-'+newcmt+'"><div class="avatar"><img src="/avatar.php?'+c+'" alt="'+a+'"/></div><div class="comment-info"><b>'+a+'</b><div class="comment-content">'+d+"</div></div></li>",f==0?$("#comments").append(c):$("#comment-"+f).children("ul")!=
void 0?$("#comment-"+f).children("ul").append(c):$("#comment-"+f).append('<ul class="children">'+c+"</ul>"),(window.opera?document.compatMode=="CSS1Compat"?$("html"):$("body"):$("html,body")).animate({scrollTop:$("#newcomment-"+newcmt).offset().top-20},"normal",function(){scrollLogo("#newcomment-"+newcmt)}),$("#comment").val(""));$("#comment_submit,#comment").attr("disabled","")});return!1}function toggleInput(){$("#userinfo").toggle("normal");return!1}
function resetLogo(){$.browser.msie&&$.browser.version=="6.0"?$(".logo").animate({top:parseInt($(document).scrollTop()+25)+"px"}):$(".logo").animate({top:"25px"});$("#message").fadeOut()}function scrollLogo(a){a=$(a).offset().top-$(document).scrollTop()-20;$.browser.msie&&$.browser.version=="6.0"&&(a+=$(document).scrollTop());$(".logo").animate({top:a+"px"})}function hideMessage(){$("#message").fadeOut(2E3)}function showMessage(a){$("#message").html(a);$("#message").fadeIn()};
jQuery.cookie=function(d,c,a){if(typeof c!="undefined"){a=a||{};if(c===null)c="",a.expires=-1;var b="";if(a.expires&&(typeof a.expires=="number"||a.expires.toUTCString))typeof a.expires=="number"?(b=new Date,b.setTime(b.getTime()+a.expires*864E5)):b=a.expires,b="; expires="+b.toUTCString();var e=a.path?"; path="+a.path:"",f=a.domain?"; domain="+a.domain:"",a=a.secure?"; secure":"";document.cookie=[d,"=",encodeURIComponent(c),b,e,f,a].join("")}else{c=null;if(document.cookie&&document.cookie!=""){a=
document.cookie.split(";");for(b=0;b<a.length;b++)if(e=jQuery.trim(a[b]),e.substring(0,d.length+1)==d+"="){c=decodeURIComponent(e.substring(d.length+1));break}}return c}};